'use strict';
// Selection sets, reusable block definitions and drafting operations.
let selectionSet=new Set(),shiftSelection=false,blockSerial=0,insertName=null;
const gid=()=>`g${Date.now().toString(36)}_${++blockSerial}`;
function chosen(){const valid=[...selectionSet].filter(i=>i>=0&&i<doc.entities.length);if(selected>=0&&!valid.includes(selected))valid.push(selected);const groups=new Set(valid.map(i=>doc.entities[i].group).filter(Boolean));doc.entities.forEach((e,i)=>{if(groups.has(e.group)&&!valid.includes(i))valid.push(i)});return valid}
function clearSelection(){selected=-1;selectionSet.clear();points=[]}
function selectAll(){selectionSet=new Set(doc.entities.map((e,i)=>i).filter(i=>doc.layers.find(l=>l.name===doc.entities[i].layer)?.visible));selected=selectionSet.values().next().value??-1;notify(`${chosen().length} entities selected`);render()}
async function createBlock(){const ids=chosen();if(!ids.length){notify('Select entities first. Shift-click adds entities, or use SELECTALL.');return}const name=await cadPrompt('Block name');if(!name?.trim())return;if(doc.blocks?.[name]){notify('A block with that name already exists.');return}const ps=ids.flatMap(i=>vertices(doc.entities[i])),base=ps[0]||{x:0,y:0},items=ids.map(i=>{const e=structuredClone(doc.entities[i]);delete e.group;transformEntity(e,p=>({x:p.x-base.x,y:p.y-base.y}));return e});mutate(()=>{doc.blocks??={};doc.blocks[name]={items};const id=gid();ids.forEach(i=>{doc.entities[i].group=id;doc.entities[i].blockName=name})});notify(`Block ${name} defined. Click Insert block to place another instance.`)}
async function startInsert(){const available=Object.keys(doc.blocks||{});if(!available.length){notify('Create a block first.');return}const name=await cadPrompt('Block name: '+available.join(', '),available[0]);if(!doc.blocks[name]){notify('Block not found.');return}insertName=name;setTool('insert');notify(`Specify insertion point for ${name}.`)}
function explode(){const ids=chosen();if(!ids.length){notify('Select a block or polyline first.');return}mutate(()=>{const result=[];doc.entities.forEach((e,i)=>{if(!ids.includes(i)){result.push(e);return}if(e.group){delete e.group;delete e.blockName;result.push(e)}else if(e.type==='polyline'){for(let j=1;j<e.points.length;j++)result.push({type:'line',layer:e.layer,points:[e.points[j-1],e.points[j]]});if(e.closed)result.push({type:'line',layer:e.layer,points:[e.points.at(-1),e.points[0]]})}else result.push(e)});doc.entities=result});clearSelection();render();notify('Exploded selected objects.')}
async function hatch(){const e=doc.entities[selected];if(!e||!(e.closed&&e.type==='polyline'||e.type==='circle')){notify('Select a closed polyline or circle boundary.');return}const raw=await cadPrompt('Hatch spacing','5');if(raw===null)return;const spacing=Number(raw);if(!Number.isFinite(spacing)||spacing<=0){notify('Enter positive spacing.');return}const ps=e.type==='circle'?Array.from({length:128},(_,i)=>({x:e.center.x+e.radius*Math.cos(i*Math.PI/64),y:e.center.y+e.radius*Math.sin(i*Math.PI/64)})):e.points;const transformed=ps.map(p=>({u:(p.x+p.y)/Math.SQRT2,v:(p.y-p.x)/Math.SQRT2})),lo=Math.min(...transformed.map(p=>p.v)),hi=Math.max(...transformed.map(p=>p.v));if((hi-lo)/spacing>3000){notify('Spacing too small; maximum 3000 hatch rows.');return}const ents=[],id=gid();for(let v=Math.ceil(lo/spacing)*spacing;v<hi;v+=spacing){const us=[];for(let i=0;i<transformed.length;i++){const a=transformed[i],b=transformed[(i+1)%transformed.length];if((a.v<=v&&b.v>v)||(b.v<=v&&a.v>v))us.push(a.u+(v-a.v)*(b.u-a.u)/(b.v-a.v))}us.sort((a,b)=>a-b);for(let i=0;i+1<us.length;i+=2)ents.push({type:'line',layer:e.layer,group:id,hatch:true,points:[us[i],us[i+1]].map(u=>({x:(u-v)/Math.SQRT2,y:(u+v)/Math.SQRT2}))})}if(!ents.length){notify('No hatch lines at this spacing.');return}mutate(()=>doc.entities.push(...ents));notify(`Hatch created: ${ents.length} editable lines.`)}
function extendAt(p){const idx=hit(p),e=doc.entities[idx];if(!e||e.type!=='line'){notify('Extend: click a line endpoint side.');return}const start=distance(p,e.points[0])<distance(p,e.points[1]),a=e.points[start?1:0],b=e.points[start?0:1],dx=b.x-a.x,dy=b.y-a.y,candidates=[];for(const other of doc.entities){if(other===e||other.type!=='line')continue;const [c,d]=other.points,ex=d.x-c.x,ey=d.y-c.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10)continue;const t=((c.x-a.x)*ey-(c.y-a.y)*ex)/den,u=((c.x-a.x)*dy-(c.y-a.y)*dx)/den;if(t>1+1e-9&&u>=0&&u<=1)candidates.push({t,x:a.x+t*dx,y:a.y+t*dy})}candidates.sort((a,b)=>a.t-b.t);if(!candidates.length){notify('No boundary line found in that direction.');return}mutate(()=>e.points[start?0:1]={x:candidates[0].x,y:candidates[0].y});notify('Line extended to nearest boundary.')}
async function chamfer(){const ids=chosen();if(ids.length!==2||ids.some(i=>doc.entities[i].type!=='line')){notify('Shift-select two lines with a shared endpoint.');return}const [e,f]=ids.map(i=>doc.entities[i]);let ei=-1,fi=-1;for(let i=0;i<2;i++)for(let j=0;j<2;j++)if(distance(e.points[i],f.points[j])<1e-7){ei=i;fi=j}if(ei<0){notify('Lines must share an endpoint.');return}const raw=await cadPrompt('Equal chamfer distance','5');if(raw===null)return;const amount=Number(raw),c=e.points[ei],a=e.points[1-ei],b=f.points[1-fi],la=distance(c,a),lb=distance(c,b);if(!Number.isFinite(amount)||amount<=0||amount>=Math.min(la,lb)){notify('Distance must be positive and shorter than both lines.');return}const A={x:c.x+(a.x-c.x)*amount/la,y:c.y+(a.y-c.y)*amount/la},B={x:c.x+(b.x-c.x)*amount/lb,y:c.y+(b.y-c.y)*amount/lb};mutate(()=>{e.points[ei]=A;f.points[fi]=B;doc.entities.push({type:'line',layer:e.layer,points:[A,B]})});notify('Chamfer created.')}
const oldCanvasDown=canvas.onpointerdown;canvas.onpointerdown=e=>{shiftSelection=e.shiftKey;oldCanvasDown(e);shiftSelection=false};
const previousAccept=accept;accept=async function(p){
if(tool==='select'){const i=hit(p);if(shiftSelection){if(selectionSet.has(i))selectionSet.delete(i);else if(i>=0)selectionSet.add(i);selected=selectionSet.values().next().value??-1}else{selectionSet.clear();selected=i;if(i>=0)selectionSet.add(i)}render();notify(`${chosen().length} entities selected. Shift-click adds or removes.`);return}
if(tool==='window'){points.push(p);if(points.length===2){const [a,b]=points;selectionSet=new Set();doc.entities.forEach((e,i)=>{const ps=e.type==='circle'?[{x:e.center.x-e.radius,y:e.center.y-e.radius},{x:e.center.x+e.radius,y:e.center.y+e.radius}]:vertices(e);if(doc.layers.find(l=>l.name===e.layer)?.visible&&ps.every(q=>q.x>=Math.min(a.x,b.x)&&q.x<=Math.max(a.x,b.x)&&q.y>=Math.min(a.y,b.y)&&q.y<=Math.max(a.y,b.y)))selectionSet.add(i)});selected=selectionSet.values().next().value??-1;points=[];notify(`${chosen().length} entities selected.`);render()}return}
if(tool==='insert'){const id=gid(),items=structuredClone(doc.blocks[insertName].items);items.forEach(e=>{transformEntity(e,q=>({x:q.x+p.x,y:q.y+p.y}));e.group=id;e.blockName=insertName;e.layer=layer().name});mutate(()=>doc.entities.push(...items));notify(`Inserted ${insertName}.`);return}
if(tool==='extend'){extendAt(p);return}
if(tool==='delete'){const idx=hit(p);if(idx<0)return;selected=idx;selectionSet=new Set([idx]);const ids=chosen();mutate(()=>doc.entities=doc.entities.filter((e,i)=>!ids.includes(i)));clearSelection();render();return}
if(['move','copy','rotate','scale','mirror'].includes(tool)){
if(selected<0){selected=hit(p);selectionSet=new Set(selected<0?[]:[selected]);render();notify('Specify base point.');return}
points.push(p);if(['move','copy','mirror'].includes(tool)&&points.length<2){notify('Specify destination / second axis point.');return}
const ids=chosen(),a=points[0];let fn,factor=1;
if(tool==='move'||tool==='copy'){const b=points[1];fn=q=>({x:q.x+b.x-a.x,y:q.y+b.y-a.y})}
if(tool==='rotate'){const raw=await cadPrompt('Rotation angle in degrees','90');if(raw===null){points=[];return}const t=Number(raw)*Math.PI/180;if(!Number.isFinite(t)){points=[];return}fn=q=>({x:a.x+(q.x-a.x)*Math.cos(t)-(q.y-a.y)*Math.sin(t),y:a.y+(q.x-a.x)*Math.sin(t)+(q.y-a.y)*Math.cos(t)})}
if(tool==='scale'){const raw=await cadPrompt('Scale factor','2');if(raw===null){points=[];return}factor=Number(raw);if(!Number.isFinite(factor)||factor<=0){points=[];notify('Positive factor required.');return}fn=q=>({x:a.x+(q.x-a.x)*factor,y:a.y+(q.y-a.y)*factor})}
if(tool==='mirror'){const b=points[1],len=distance(a,b);if(len<1e-9){points=[];return}const ux=(b.x-a.x)/len,uy=(b.y-a.y)/len;fn=q=>{const vx=q.x-a.x,vy=q.y-a.y,dot=vx*ux+vy*uy;return{x:a.x+2*dot*ux-vx,y:a.y+2*dot*uy-vy}}}
mutate(()=>{const groups={};for(const i of ids){const e=tool==='copy'?structuredClone(doc.entities[i]):doc.entities[i];transformEntity(e,fn);if(e.type==='circle')e.radius*=factor;if(e.type==='text')e.height*=factor;if(tool==='copy'){if(e.group)e.group=groups[e.group]??=gid();doc.entities.push(e)}}});points=[];notify(`${ids.length} entities ${tool==='copy'?'copied':'transformed'}.`);return}
previousAccept(p)};
const earlierDraw=drawEntity;drawEntity=function(e,color,dashed){const ids=chosen();if(ids.some(i=>doc.entities[i]===e))color='#ffcb66';earlierDraw(e,color,dashed)};
const previousKeys=document.onkeydown;document.onkeydown=e=>{if(e.target.matches('input,select')){previousKeys(e);return}if(e.ctrlKey&&e.key.toLowerCase()==='a'){e.preventDefault();selectAll();return}if(e.key==='Escape')selectionSet.clear();if(e.key==='Delete'){const ids=chosen();if(ids.length){mutate(()=>doc.entities=doc.entities.filter((e,i)=>!ids.includes(i)));clearSelection();render();return}}previousKeys(e)};
// Save view-based layout presets and print on a white sheet.
async function saveLayout(){const name=await cadPrompt('Layout name','Sheet 1');if(!name)return;mutate(()=>{doc.layouts??={};doc.layouts[name]={view:structuredClone(view),paper:'A4',landscape:true}});notify(`Layout ${name} saved with current view.`)}
async function restoreLayout(){const keys=Object.keys(doc.layouts||{});if(!keys.length){notify('Save a layout first.');return}const name=await cadPrompt('Layout: '+keys.join(', '),keys[0]);if(!doc.layouts[name])return;view=structuredClone(doc.layouts[name].view);dt.textContent=name+' / Saved model view';render();notify('Layout view restored. Layouts save view extents, not separate paper-space entities.')}
async function plotSheet(){const raw=await cadPrompt('Paper size: A4, A3 or LETTER','A4');if(!raw)return;const paper=raw.toUpperCase();if(!['A4','A3','LETTER'].includes(paper)){notify('Unsupported paper size.');return}const win=window.open('','_blank');if(!win){notify('Allow pop-ups to open the print sheet.');return}const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));let svg='';for(const e of doc.entities){if(!doc.layers.find(l=>l.name===e.layer)?.visible)continue;if(e.type==='circle')svg+=`<circle cx="${e.center.x}" cy="${-e.center.y}" r="${e.radius}"/>`;else if(e.type==='text')svg+=`<text x="${e.points[0].x}" y="${-e.points[0].y}" font-size="${e.height}" fill="black" stroke="none">${esc(e.text)}</text>`;else svg+=`<${e.closed?'polygon':'polyline'} points="${e.points.map(p=>p.x+','+-p.y).join(' ')}"/>`}const w=W/view.scale,h=H/view.scale;win.document.write(`<!doctype html><title>CadForge Print Sheet</title><style>@page{size:${paper==='LETTER'?'letter':paper} landscape;margin:12mm}body{margin:0;font:12px Arial}svg{width:100%;height:85vh}button{padding:10px;margin:10px}@media print{button{display:none}svg{height:160mm}}</style><button onclick="window.print()">Print / Save as PDF</button><svg xmlns="http://www.w3.org/2000/svg" viewBox="${view.x-w/2} ${-view.y-h/2} ${w} ${h}" fill="none" stroke="black" stroke-width="${.7/view.scale}">${svg}</svg>`);win.document.close();notify('Print sheet opened. Use Print / Save as PDF.')}
names.window='Window select';names.insert='Insert block';names.extend='Extend';
group('Blocks / Drafting',[['Window select',()=>setTool('window'),'window'],['Select all',selectAll],['Create block',createBlock],['Insert block',startInsert],['Explode',explode],['Hatch',hatch],['Extend',()=>setTool('extend'),'extend'],['Chamfer',chamfer]]);
group('Layouts',[['Save layout',saveLayout],['Restore layout',restoreLayout],['Print sheet',plotSheet],['Model',()=>{dt.textContent='Drawing 1 / Model space';fit()}]]);
const advancedCommand=$('command').onkeydown;$('command').onkeydown=e=>{if(e.key==='Enter'){const s=e.target.value.trim().toLowerCase(),actions={selectall:selectAll,block:createBlock,insert:startInsert,explode,hatch,chamfer,layout:saveLayout,restorelayout:restoreLayout,plot:plotSheet};if(actions[s]){e.target.value='';actions[s]();return}if(s==='ex')e.target.value='extend'}advancedCommand(e)};
const origValidate=validate;validate=function(d){origValidate(d);if(d.blocks){if(typeof d.blocks!=='object'||Array.isArray(d.blocks))throw Error('Invalid blocks');for(const block of Object.values(d.blocks))origValidate({layers:d.layers,entities:block.items})}if(d.layouts){for(const l of Object.values(d.layouts)){if(!l.view||![l.view.x,l.view.y,l.view.scale].every(Number.isFinite)||l.view.scale<=0)throw Error('Invalid layout')}}};
// Explicit tab mappings include the new functional panels.
for(const b of tabbar.querySelectorAll('button'))b.onclick=()=>{tabbar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));ribbon.querySelectorAll('.rgroup').forEach((g,i)=>{g.style.display=b.textContent==='Home'||(b.textContent==='Insert'&&[0,5].includes(i))||(b.textContent==='Annotate'&&[2,5].includes(i))||(b.textContent==='View'&&[3,6].includes(i))||(b.textContent==='Manage'&&[4,6].includes(i))?'block':'none'})};
notify('Ready. Shift-click for multiple selection; blocks, hatching and saved layouts available.');render();

