'use strict';
// Adapt CadForge triangle meshes to the bundled MIT-licensed csg.js library.
function meshToCSG(mesh){return CSG.fromPolygons(mesh.faces.map(f=>{const ps=f.map(i=>new CSG.Vector(mesh.vertices[i])),n=ps[1].minus(ps[0]).cross(ps[2].minus(ps[0]));if(n.length()<1e-10)return null;const normal=n.unit();return new CSG.Polygon(ps.map(p=>new CSG.Vertex(p,normal)))}).filter(Boolean))}
function csgToMesh(csg,name,color){const vertices=[],faces=[],lookup=new Map();function index(p){const key=[p.x,p.y,p.z].map(v=>v.toFixed(8)).join(',');if(lookup.has(key))return lookup.get(key);const i=vertices.length;vertices.push({x:p.x,y:p.y,z:p.z});lookup.set(key,i);return i}for(const polygon of csg.toPolygons()){const ids=polygon.vertices.map(v=>index(v.pos));for(let i=1;i+1<ids.length;i++){const a=vertices[ids[0]],b=vertices[ids[i]],c=vertices[ids[i+1]],u={x:b.x-a.x,y:b.y-a.y,z:b.z-a.z},v={x:c.x-a.x,y:c.y-a.y,z:c.z-a.z},area=Math.hypot(u.y*v.z-u.z*v.y,u.z*v.x-u.x*v.z,u.x*v.y-u.y*v.x);if(area>1e-10)faces.push([ids[0],ids[i],ids[i+1]])}}return{name,color,vertices,faces}}
function booleanMeshes(a,b,operation){if(!['union','subtract','intersect'].includes(operation))throw Error('Invalid operation.');if(a.faces.length+b.faces.length>5000)throw Error('Mesh boolean limit: 5000 input triangles.');return csgToMesh(meshToCSG(a)[operation](meshToCSG(b)),operation+' result',a.color)}
const meshPanel=document.createElement('div');meshPanel.innerHTML='<hr><strong>MESH OPERATIONS</strong><label for="meshA">Mesh A</label><select id="meshA"></select><label for="meshB">Mesh B</label><select id="meshB"></select><small>Boolean operations replace A and B with the result. Undo restores operands.</small><div id="booleanButtons"></div>';
props.append(meshPanel);
for(const op of ['union','subtract','intersect']){const b=document.createElement('button');b.textContent=op==='subtract'?'Subtract A − B':op[0].toUpperCase()+op.slice(1);b.onclick=()=>applyBoolean(op);$('booleanButtons').append(b)}
function syncMeshChoices(){for(const [id,defaultIndex]of [['meshA',0],['meshB',1]]){const old=$(id).value;$(id).replaceChildren(...(doc.solids||[]).map((s,i)=>new Option(`${i+1}: ${s.name}`,String(i))));$(id).value=old!==''&&Number.isInteger(Number(old))&&Number(old)>=0&&Number(old)<(doc.solids||[]).length?old:String(Math.min(defaultIndex,(doc.solids||[]).length-1))}}
function applyBoolean(op){const ia=Number($('meshA').value),ib=Number($('meshB').value),a=doc.solids?.[ia],b=doc.solids?.[ib];if(!a||!b||ia===ib){notify('Choose two different meshes in the properties panel.');return}try{const result=booleanMeshes(a,b,op);mutate(()=>{doc.solids=doc.solids.filter((s,i)=>i!==ia&&i!==ib);if(result.faces.length)doc.solids.push(result)});show3D();notify(result.faces.length?`${op} complete: ${result.faces.length} triangles.`:'Boolean result is empty; operands removed. Undo restores them.')}catch(err){notify('Boolean failed: '+err.message)}}
async function translateMesh(){const e=doc.solids?.[Number($('meshA').value)];if(!e){notify('Choose Mesh A first.');return}const raw=await cadPrompt('Mesh displacement dx,dy,dz','0,0,0');if(raw===null)return;const delta=raw.split(',').map(Number);if(delta.length!==3||!delta.every(Number.isFinite)){notify('Enter three finite numbers.');return}mutate(()=>e.vertices.forEach(p=>{p.x+=delta[0];p.y+=delta[1];p.z+=delta[2]}));show3D()}
function duplicateMesh(){const e=doc.solids?.[Number($('meshA').value)];if(!e){notify('Choose Mesh A first.');return}mutate(()=>{const copy=structuredClone(e);copy.name+=' copy';doc.solids.push(copy)});show3D()}
function exportSTL(){if(!doc.solids?.length){notify('Create meshes first.');return}const out=['solid CadForge'];for(const mesh of doc.solids)for(const f of mesh.faces){const ps=f.map(i=>new CSG.Vector(mesh.vertices[i])),n=ps[1].minus(ps[0]).cross(ps[2].minus(ps[0])).unit();out.push(`facet normal ${n.x} ${n.y} ${n.z}`,' outer loop',...ps.map(p=>`  vertex ${p.x} ${p.y} ${p.z}`),' endloop','endfacet')}out.push('endsolid CadForge');download('drawing.stl',out.join('\n')+'\n','model/stl')}
group('Mesh editing',[['Union',()=>applyBoolean('union')],['Subtract',()=>applyBoolean('subtract')],['Intersect',()=>applyBoolean('intersect')],['Move mesh',translateMesh],['Copy mesh',duplicateMesh],['Export STL',exportSTL]]);
const boolRender=render;render=function(){boolRender();if(document.activeElement?.id!=='meshA'&&document.activeElement?.id!=='meshB')syncMeshChoices()};
const boolCommand=$('command').onkeydown;$('command').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const s=e.target.value.trim().toLowerCase(),actions={union:()=>applyBoolean('union'),subtract:()=>applyBoolean('subtract'),intersect:()=>applyBoolean('intersect'),movemesh:translateMesh,copymesh:duplicateMesh,stl:exportSTL};if(actions[s]){e.target.value='';actions[s]();return}}boolCommand(e)};
for(const b of tabbar.querySelectorAll('button'))b.onclick=()=>{tabbar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));ribbon.querySelectorAll('.rgroup').forEach((g,i)=>{g.style.display=(b.textContent==='Home'&&[0,1,2,3].includes(i))||(b.textContent==='Insert'&&[0,5].includes(i))||(b.textContent==='Annotate'&&[2,5].includes(i))||(b.textContent==='View'&&[3,6,7,8].includes(i))||(b.textContent==='Manage'&&[4,6,7,8].includes(i))?'block':'none'})};
syncMeshChoices();tabbar.querySelector('button').click();

