'use strict';
// DXF block instances plus tessellated ARC and bulged-polyline import.
function dxfRecords(text){if(text.startsWith('AutoCAD Binary DXF'))throw Error('Binary DXF is unsupported. Export ASCII DXF.');const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/),records=[];let r;for(let i=0;i+1<lines.length;i+=2){const k=Number(lines[i].trim()),v=lines[i+1].trim();if(!Number.isInteger(k))throw Error('Malformed DXF group code.');if(k===0){r={type:v,pairs:[]};records.push(r)}else if(r)r.pairs.push([k,v])}return records}
function dxfValue(r,k,defaultValue=0){return r.pairs.find(p=>p[0]===k)?.[1]??defaultValue}
function dxfRecordText(r){return ['0',r.type,...r.pairs.flatMap(([k,v])=>[String(k),String(v)])].join('\r\n')+'\r\n'}
function dxfWrapped(records,tables=[]){return '0\r\nSECTION\r\n2\r\nTABLES\r\n'+tables.map(dxfRecordText).join('')+'0\r\nENDSEC\r\n0\r\nSECTION\r\n2\r\nENTITIES\r\n'+records.map(dxfRecordText).join('')+'0\r\nENDSEC\r\n0\r\nEOF\r\n'}
function bulgeSegment(a,b,bulge){if(Math.abs(bulge)<1e-12)return[a,b];const chord=distance(a,b);if(chord<1e-12)return[a];const theta=4*Math.atan(bulge),ux=(b.x-a.x)/chord,uy=(b.y-a.y)/chord,offset=chord*(1-bulge*bulge)/(4*bulge),center={x:(a.x+b.x)/2-uy*offset,y:(a.y+b.y)/2+ux*offset},radius=distance(a,center),start=Math.atan2(a.y-center.y,a.x-center.x),steps=Math.min(2048,Math.max(4,Math.ceil(Math.abs(theta)*32)));return Array.from({length:steps+1},(_,i)=>{if(i===0)return{x:a.x,y:a.y};if(i===steps)return{x:b.x,y:b.y};const t=start+theta*i/steps;return{x:center.x+radius*Math.cos(t),y:center.y+radius*Math.sin(t)}})}
const simpleDXFImport=importDXF;
importDXF=function(text){const records=dxfRecords(text),defs=new Map(),tables=[],model=[];let section='',current=null;for(const r of records){if(r.type==='SECTION'){section=dxfValue(r,2,'');continue}if(r.type==='ENDSEC'){section='';current=null;continue}if(section==='TABLES')tables.push(r);else if(section==='BLOCKS'){if(r.type==='BLOCK'){current={name:String(dxfValue(r,2,'')),base:{x:Number(dxfValue(r,10)),y:Number(dxfValue(r,20))},records:[]};defs.set(current.name,current)}else if(r.type==='ENDBLK')current=null;else if(current)current.records.push(r)}else if(section==='ENTITIES')model.push(r)}let skipped=0,approximated=0,expanded=0;const layers=simpleDXFImport(dxfWrapped([],tables)).doc.layers;
function parse(rs,depth=0){if(depth>16)throw Error('Nested block limit exceeded.');const entities=[];let primitive=[];function flush(){if(!primitive.length)return;const res=simpleDXFImport(dxfWrapped(primitive,tables));entities.push(...res.doc.entities);skipped+=res.skipped;primitive=[]}for(const r of rs){if(r.type==='ARC'){flush();const c={x:Number(dxfValue(r,10)),y:Number(dxfValue(r,20))},radius=Number(dxfValue(r,40)),start=Number(dxfValue(r,50))*Math.PI/180;let end=Number(dxfValue(r,51))*Math.PI/180;while(end<=start)end+=Math.PI*2;const steps=Math.min(2048,Math.max(4,Math.ceil((end-start)*32)));entities.push({type:'polyline',layer:String(dxfValue(r,8,'0')),closed:false,points:Array.from({length:steps+1},(_,i)=>({x:c.x+radius*Math.cos(start+(end-start)*i/steps),y:c.y+radius*Math.sin(start+(end-start)*i/steps)}))});approximated++;continue}
if(r.type==='LWPOLYLINE'&&r.pairs.some(([k,v])=>k===42&&Number(v)!==0)){flush();const vertices=[];for(const [k,v]of r.pairs){if(k===10)vertices.push({x:Number(v),y:0,bulge:0});else if(k===20&&vertices.length)vertices.at(-1).y=Number(v);else if(k===42&&vertices.length)vertices.at(-1).bulge=Number(v)}const closed=!!(Number(dxfValue(r,70))&1),ps=[];for(let i=0;i<vertices.length-(closed?0:1);i++){const samples=bulgeSegment(vertices[i],vertices[(i+1)%vertices.length],vertices[i].bulge);ps.push(...samples.slice(0,-1))}if(!closed&&vertices.length)ps.push({x:vertices.at(-1).x,y:vertices.at(-1).y});entities.push({type:'polyline',layer:String(dxfValue(r,8,'0')),closed,points:ps});approximated++;continue}
if(r.type==='INSERT'){flush();const name=String(dxfValue(r,2,'')),def=defs.get(name);if(!def){skipped++;continue}if(Number(dxfValue(r,70,1))!==1||Number(dxfValue(r,71,1))!==1){skipped++;continue}const items=parse(def.records,depth+1),sx=Number(dxfValue(r,41,1)),sy=Number(dxfValue(r,42,1)),angle=Number(dxfValue(r,50))*Math.PI/180,tx=Number(dxfValue(r,10)),ty=Number(dxfValue(r,20)),id=gid(),insertLayer=String(dxfValue(r,8,'0'));const fn=p=>{const x=(p.x-def.base.x)*sx,y=(p.y-def.base.y)*sy;return{x:tx+x*Math.cos(angle)-y*Math.sin(angle),y:ty+x*Math.sin(angle)+y*Math.cos(angle)}};for(let e of items){if(e.type==='circle'&&Math.abs(Math.abs(sx)-Math.abs(sy))>1e-8){const ps=Array.from({length:128},(_,i)=>({x:e.center.x+e.radius*Math.cos(i*Math.PI/64),y:e.center.y+e.radius*Math.sin(i*Math.PI/64)}));e={type:'polyline',points:ps,closed:true,layer:e.layer};approximated++}transformEntity(e,fn);if(e.type==='circle')e.radius*=Math.abs(sx);if(e.type==='text')e.height*=Math.abs(sy);if(e.layer==='0')e.layer=insertLayer;e.group=id;e.blockName=name;entities.push(e);if(++expanded>200000)throw Error('Expanded block entity limit exceeded.')}continue}primitive.push(r)}flush();return entities}
const entities=parse(model),blocks={};for(const def of defs.values()){if(def.name.startsWith('*'))continue;const items=parse(def.records).map(e=>{const clone=structuredClone(e);delete clone.group;delete clone.blockName;transformEntity(clone,p=>({x:p.x-def.base.x,y:p.y-def.base.y}));return clone});blocks[def.name]={items}}for(const e of [...entities,...Object.values(blocks).flatMap(b=>b.items)])if(!layers.some(l=>l.name===e.layer))layers.push({name:e.layer,color:'#63d9c0',visible:true});const result={layers,entities,blocks};validate(result);return{doc:result,skipped,approximated}}
const primitiveExport=exportDXF;
function primitiveDXFText(items){const original=doc;try{doc={layers:original.layers,entities:items};const text=primitiveExport(),marker='0\r\nSECTION\r\n2\r\nENTITIES\r\n';return text.split(marker)[1].split('0\r\nENDSEC\r\n')[0]}finally{doc=original}}
exportDXF=function(){const text=primitiveExport(),groups=new Map(),loose=[];for(const e of doc.entities){if(e.group){if(!groups.has(e.group))groups.set(e.group,[]);groups.get(e.group).push(e)}else loose.push(e)}let definitions='',instances='',serial=0;for(const items of groups.values()){const name='CF_INSTANCE_'+(++serial);definitions+=`0\r\nBLOCK\r\n8\r\n0\r\n2\r\n${name}\r\n70\r\n0\r\n10\r\n0\r\n20\r\n0\r\n30\r\n0\r\n3\r\n${name}\r\n1\r\n\r\n`+primitiveDXFText(items)+'0\r\nENDBLK\r\n8\r\n0\r\n';instances+=`0\r\nINSERT\r\n8\r\n0\r\n2\r\n${name}\r\n10\r\n0\r\n20\r\n0\r\n30\r\n0\r\n`}const marker='0\r\nSECTION\r\n2\r\nENTITIES\r\n',prefix=text.split(marker)[0];return prefix+'0\r\nSECTION\r\n2\r\nBLOCKS\r\n'+definitions+'0\r\nENDSEC\r\n'+marker+primitiveDXFText(loose)+instances+'0\r\nENDSEC\r\n0\r\nEOF\r\n'};
$('file').accept='.json,.dxf,.dwg';$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.name.toLowerCase().endsWith('.dwg'))throw Error('Native DWG needs a DWG engine. Export ASCII DXF from your CAD application first.');const text=await f.text(),res=f.name.toLowerCase().endsWith('.dxf')?importDXF(text):{doc:JSON.parse(text),skipped:0,approximated:0};validate(res.doc);clearSelection();mode3D=false;mutate(()=>doc=res.doc);syncLayers();showModel();notify(`Imported ${doc.entities.length} entities. ${res.skipped||0} unsupported records; ${res.approximated||0} curve approximations. Inspect before use.`)}catch(err){notify('Import failed: '+err.message)}e.target.value=''};
// Clearer workspace labels and compact Home ribbon.
document.querySelector('header span').textContent='Drafting & mesh modeling';
for(const b of tabbar.querySelectorAll('button'))b.onclick=()=>{tabbar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));ribbon.querySelectorAll('.rgroup').forEach((g,i)=>{g.style.display=(b.textContent==='Home'&&[0,1,2,3].includes(i))||(b.textContent==='Insert'&&[0,5].includes(i))||(b.textContent==='Annotate'&&[2,5].includes(i))||(b.textContent==='View'&&[3,6,7].includes(i))||(b.textContent==='Manage'&&[4,6,7].includes(i))?'block':'none'})};
tabbar.querySelector('button').click();
