
'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let doc={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[]},history=[],future=[],tool='select',points=[],selected=-1,mouse={x:0,y:0},pan=null,view={x:0,y:0,scale:4},W=0,H=0;
const names={select:'Select',line:'Line',polyline:'Polyline',rectangle:'Rectangle',circle:'Circle',text:'Text',move:'Move',copy:'Copy',delete:'Erase'};
const layer=()=>doc.layers.find(l=>l.name===$('layer').value)||doc.layers[0], distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function notify(s){$('hint').textContent=s}function persist(){try{localStorage.setItem('cadforge',JSON.stringify(doc))}catch(e){notify('Autosave unavailable; use Save project.')}}
function checkpoint(){history.push(JSON.stringify(doc));if(history.length>100)history.shift();future=[]}
function mutate(fn){checkpoint();fn();persist();render()}
function syncLayers(){const old=$('layer').value;$('layer').replaceChildren(...doc.layers.map(l=>new Option(l.name,l.name)));if(doc.layers.some(l=>l.name===old))$('layer').value=old;$('color').value=layer().color;$('visible').checked=layer().visible}
function setTool(t){tool=t;points=[];document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));notify(t==='select'?'Select an entity.':t==='move'||t==='copy'?'Select an entity, then specify base and destination.':t==='polyline'?'Specify vertices; Enter finishes polyline.':`Specify ${names[t].toLowerCase()} points.`);render()}
for(const [t,n]of Object.entries(names)){const b=document.createElement('button');b.textContent=n;b.dataset.tool=t;b.onclick=()=>setTool(t);$('tools').append(b)}
function screen(p){return{x:W/2+(p.x-view.x)*view.scale,y:H/2-(p.y-view.y)*view.scale}}function world(p){return{x:view.x+(p.x-W/2)/view.scale,y:view.y-(p.y-H/2)/view.scale}}
function vertices(e){if(e.type==='circle')return[e.center];return e.points||[]}
function snap(p){if($('snap').checked){let best=null,d=10/view.scale;for(const e of doc.entities){if(!doc.layers.find(l=>l.name===e.layer)?.visible)continue;for(const q of vertices(e)){const n=distance(p,q);if(n<d){d=n;best=q}}}p=best?{...best}:{x:Math.round(p.x/5)*5,y:Math.round(p.y/5)*5}}if($('ortho').checked&&points.length){const a=points[points.length-1];if(Math.abs(p.x-a.x)>Math.abs(p.y-a.y))p.y=a.y;else p.x=a.x}return p}
function segmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return distance(p,{x:a.x+t*dx,y:a.y+t*dy})}
function hit(p){let idx=-1,best=9/view.scale;doc.entities.forEach((e,i)=>{if(!doc.layers.find(l=>l.name===e.layer)?.visible)return;let d=Infinity;if(e.type==='circle')d=Math.abs(distance(p,e.center)-e.radius);else if(e.type==='text')d=distance(p,e.points[0]);else{for(let j=1;j<e.points.length;j++)d=Math.min(d,segmentDistance(p,e.points[j-1],e.points[j]));if(e.closed)d=Math.min(d,segmentDistance(p,e.points.at(-1),e.points[0]))}if(d<best){best=d;idx=i}});return idx}
function drawEntity(e,color,dashed=false){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.5;ctx.setLineDash(dashed?[6,5]:[]);ctx.beginPath();if(e.type==='circle'){const p=screen(e.center);ctx.arc(p.x,p.y,e.radius*view.scale,0,Math.PI*2)}else if(e.type==='text'){const p=screen(e.points[0]);ctx.font=`${e.height*view.scale}px Segoe UI`;ctx.fillText(e.text,p.x,p.y)}else{e.points.forEach((p,i)=>{const q=screen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});if(e.closed)ctx.closePath()}ctx.stroke();ctx.setLineDash([])}
function shape(t,a,b){if(t==='circle')return{type:'circle',center:a,radius:distance(a,b)};if(t==='rectangle')return{type:'polyline',points:[a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}],closed:true};return{type:t==='polyline'?'polyline':'line',points:[a,b]}}
function render(){ctx.clearRect(0,0,W,H);let step=5;while(step*view.scale<22)step*=2;ctx.strokeStyle='#202c3a';ctx.lineWidth=1;const min=world({x:0,y:H}),max=world({x:W,y:0});ctx.beginPath();for(let x=Math.ceil(min.x/step)*step;x<max.x;x+=step){const p=screen({x,y:0});ctx.moveTo(p.x,0);ctx.lineTo(p.x,H)}for(let y=Math.ceil(min.y/step)*step;y<max.y;y+=step){const p=screen({x:0,y});ctx.moveTo(0,p.y);ctx.lineTo(W,p.y)}ctx.stroke();const o=screen({x:0,y:0});ctx.strokeStyle='#45546a';ctx.beginPath();ctx.moveTo(o.x,0);ctx.lineTo(o.x,H);ctx.moveTo(0,o.y);ctx.lineTo(W,o.y);ctx.stroke();doc.entities.forEach((e,i)=>{const l=doc.layers.find(l=>l.name===e.layer);if(l?.visible)drawEntity(e,i===selected?'#ffcb66':l.color)});if(points.length&&['line','rectangle','circle','polyline'].includes(tool)){const e=tool==='polyline'?{type:'polyline',points:[...points,mouse]}:shape(tool,points[0],mouse);drawEntity(e,'#ffffff',true)}const c=screen(mouse);ctx.strokeStyle='#b8cadb';ctx.beginPath();ctx.moveTo(c.x-9,c.y);ctx.lineTo(c.x+9,c.y);ctx.moveTo(c.x,c.y-9);ctx.lineTo(c.x,c.y+9);ctx.stroke();$('status').textContent=`X ${mouse.x.toFixed(2)} Y ${mouse.y.toFixed(2)} | ${doc.entities.length} entities`}
function add(e){e.layer=layer().name;mutate(()=>doc.entities.push(e))}
async function accept(p){if(tool==='select'||tool==='delete'){selected=hit(p);if(tool==='delete'&&selected>=0){mutate(()=>doc.entities.splice(selected,1));selected=-1}render();return}if(tool==='move'||tool==='copy'){if(selected<0){selected=hit(p);render();return}points.push(p);if(points.length===2){const dx=p.x-points[0].x,dy=p.y-points[0].y;mutate(()=>{const e=tool==='copy'?structuredClone(doc.entities[selected]):doc.entities[selected];if(e.center){e.center.x+=dx;e.center.y+=dy}else e.points.forEach(q=>{q.x+=dx;q.y+=dy});if(tool==='copy')doc.entities.push(e)});points=[]}return}if(tool==='text'){const text=await cadPrompt('Text');if(text)add({type:'text',points:[p],text,height:5});return}points.push(p);if(tool!=='polyline'&&points.length===2){const e=shape(tool,points[0],p);if(distance(points[0],p)>1e-9)add(e);points=[]}render()}
function finish(){if(tool==='polyline'&&points.length>1)add({type:'polyline',points:[...points],closed:false});points=[];render()}
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);if(e.button===1||e.button===2){pan={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};return}accept(mouse=snap(world({x:e.offsetX,y:e.offsetY})))};
canvas.onpointermove=e=>{if(pan){view.x=pan.vx-(e.clientX-pan.x)/view.scale;view.y=pan.vy+(e.clientY-pan.y)/view.scale}else mouse=snap(world({x:e.offsetX,y:e.offsetY}));render()};canvas.onpointerup=()=>pan=null;canvas.onpointercancel=()=>pan=null;canvas.oncontextmenu=e=>e.preventDefault();
canvas.onwheel=e=>{e.preventDefault();const p={x:e.offsetX,y:e.offsetY},a=world(p);view.scale=Math.max(.01,Math.min(1000,view.scale*Math.exp(-e.deltaY*.001)));const b=world(p);view.x+=a.x-b.x;view.y+=a.y-b.y;render()};
function fit(){const p=doc.entities.flatMap(e=>e.type==='circle'?[{x:e.center.x-e.radius,y:e.center.y-e.radius},{x:e.center.x+e.radius,y:e.center.y+e.radius}]:e.type==='text'?[e.points[0],{x:e.points[0].x+e.text.length*e.height*.6,y:e.points[0].y+e.height}]:vertices(e));if(!p.length){view={x:0,y:0,scale:4};render();return}const xs=p.map(q=>q.x),ys=p.map(q=>q.y),a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys);view={x:(a+b)/2,y:(c+d)/2,scale:Math.max(.01,Math.min(1000,Math.min(W/Math.max(20,b-a),H/Math.max(20,d-c))*.8))};render()}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(JSON.stringify(doc));doc=JSON.parse(from.pop());selected=-1;points=[];syncLayers();persist();render()}
$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);$('fit').onclick=fit;
$('layer').onchange=()=>{syncLayers();render()};$('color').onchange=()=>mutate(()=>layer().color=$('color').value);$('visible').onchange=()=>mutate(()=>layer().visible=$('visible').checked);$('addLayer').onclick=async()=>{const name=await cadPrompt('Layer name');if(name&&!doc.layers.some(l=>l.name===name)){mutate(()=>doc.layers.push({name,color:'#63d9c0',visible:true}));syncLayers();$('layer').value=name;syncLayers()}};
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('save').onclick=()=>download('drawing.cadforge.json',JSON.stringify(doc,null,2),'application/json');$('new').onclick=async()=>{if((doc.entities.length||doc.solids?.length)&&!await cadConfirm('Clear drawing? Save first if needed.'))return;mutate(()=>doc={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[]});selected=-1;points=[];syncLayers();fit()};
function exportDXF(){const out=[],pair=(k,v)=>out.push(String(k),String(v));pair(0,'SECTION');pair(2,'HEADER');pair(9,'$ACADVER');pair(1,'AC1009');pair(0,'ENDSEC');pair(0,'SECTION');pair(2,'TABLES');pair(0,'TABLE');pair(2,'LAYER');pair(70,doc.layers.length);for(const l of doc.layers){pair(0,'LAYER');pair(2,l.name);pair(70,0);pair(62,l.visible?7:-7);pair(6,'CONTINUOUS')}pair(0,'ENDTAB');pair(0,'ENDSEC');pair(0,'SECTION');pair(2,'ENTITIES');for(const e of doc.entities){pair(0,e.type==='circle'?'CIRCLE':e.type==='text'?'TEXT':e.type==='line'?'LINE':'POLYLINE');pair(8,e.layer);if(e.type==='circle'){pair(10,e.center.x);pair(20,e.center.y);pair(30,0);pair(40,e.radius)}else if(e.type==='text'){pair(10,e.points[0].x);pair(20,e.points[0].y);pair(30,0);pair(40,e.height);pair(1,e.text)}else if(e.type==='line'){pair(10,e.points[0].x);pair(20,e.points[0].y);pair(30,0);pair(11,e.points[1].x);pair(21,e.points[1].y);pair(31,0)}else{pair(66,1);pair(70,e.closed?1:0);pair(10,0);pair(20,0);pair(30,0);for(const p of e.points){pair(0,'VERTEX');pair(8,e.layer);pair(10,p.x);pair(20,p.y);pair(30,0)}pair(0,'SEQEND');pair(8,e.layer)}}pair(0,'ENDSEC');pair(0,'EOF');return out.join('\r\n')+'\r\n'}
function importDXF(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/),records=[];let r=null;for(let i=0;i+1<lines.length;i+=2){const k=Number(lines[i].trim()),v=lines[i+1].trim();if(k===0){r={type:v,pairs:[]};records.push(r)}else if(r)r.pairs.push([k,v])}const result={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[]};let poly=null,section='',skipped=0;const val=(r,k,def=0)=>r.pairs.find(p=>p[0]===k)?.[1]??def,num=(r,k,def=0)=>Number(val(r,k,def)),pt=(r,k=10)=>({x:num(r,k),y:num(r,k+10)});for(const r of records){if(r.type==='SECTION'){section=val(r,2,'');continue}if(r.type==='ENDSEC'){section='';poly=null;continue}if(section==='TABLES'&&r.type==='LAYER'){const name=val(r,2,'0');const l={name,color:'#63d9c0',visible:num(r,62,7)>0};const i=result.layers.findIndex(x=>x.name===name);if(i>=0)result.layers[i]=l;else result.layers.push(l);continue}if(section!=='ENTITIES')continue;const name=String(val(r,8,'0'));if(!result.layers.some(l=>l.name===name))result.layers.push({name,color:'#63d9c0',visible:true});let e;if(r.type==='LINE')e={type:'line',points:[pt(r),pt(r,11)]};else if(r.type==='CIRCLE')e={type:'circle',center:pt(r),radius:num(r,40)};else if(r.type==='TEXT')e={type:'text',points:[pt(r)],text:String(val(r,1,'')),height:num(r,40,5)};else if(r.type==='POLYLINE'){e={type:'polyline',points:[],closed:!!(num(r,70)&1)};poly=e}else if(r.type==='VERTEX'&&poly){poly.points.push(pt(r));continue}else if(r.type==='SEQEND'){poly=null;continue}else if(r.type==='LWPOLYLINE'){const ps=[];for(const [k,v]of r.pairs){if(k===10)ps.push({x:Number(v),y:0});if(k===20&&ps.length)ps.at(-1).y=Number(v)}e={type:'polyline',points:ps,closed:!!(num(r,70)&1)};if(r.pairs.some(([k,v])=>k===42&&Number(v)!==0))skipped++}else{skipped++;continue}e.layer=name;result.entities.push(e)}result.entities=result.entities.filter(e=>e.type!=='polyline'||e.points.length>1);validate(result);return{doc:result,skipped}}
function validate(d){if(!d||!Array.isArray(d.layers)||!d.layers.length||!Array.isArray(d.entities))throw Error('Invalid project');const finite=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y);for(const l of d.layers)if(typeof l.name!=='string'||!/^#[0-9a-f]{6}$/i.test(l.color)||typeof l.visible!=='boolean')throw Error('Invalid layer');for(const e of d.entities){if(!d.layers.some(l=>l.name===e.layer))throw Error('Missing layer');if(e.type==='circle'){if(!finite(e.center)||!Number.isFinite(e.radius)||e.radius<=0)throw Error('Invalid circle')}else if(!['line','polyline','text'].includes(e.type)||!Array.isArray(e.points)||!e.points.every(finite)||e.points.length<(e.type==='text'?1:2))throw Error('Invalid entity');if(e.type==='text'&&(typeof e.text!=='string'||!Number.isFinite(e.height)||e.height<=0))throw Error('Invalid text')}}
$('dxf').onclick=()=>download('drawing.dxf',exportDXF(),'application/dxf');$('open').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const text=await f.text(),r=f.name.toLowerCase().endsWith('.dxf')?importDXF(text):{doc:JSON.parse(text),skipped:0};validate(r.doc);mutate(()=>doc=r.doc);selected=-1;points=[];syncLayers();fit();notify(r.skipped?`Imported with ${r.skipped} unsupported records or curved polylines; inspect geometry.`:'Drawing imported.')}catch(err){notify('Import failed: '+err.message)}e.target.value=''};
$('svg').onclick=()=>{const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));const elements=doc.entities.filter(e=>doc.layers.find(l=>l.name===e.layer)?.visible).map(e=>{const color=doc.layers.find(l=>l.name===e.layer).color;if(e.type==='circle')return `<circle cx="${e.center.x}" cy="${-e.center.y}" r="${e.radius}" stroke="${color}" fill="none"/>`;if(e.type==='text')return `<text x="${e.points[0].x}" y="${-e.points[0].y}" font-size="${e.height}" fill="${color}">${esc(e.text)}</text>`;return `<${e.closed?'polygon':'polyline'} points="${e.points.map(p=>p.x+','+-p.y).join(' ')}" stroke="${color}" fill="none"/>`});download('drawing.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view.x-W/2/view.scale} ${-view.y-H/2/view.scale} ${W/view.scale} ${H/view.scale}" stroke-width="${1/view.scale}">${elements.join('')}</svg>`,'image/svg+xml')};
$('command').onkeydown=e=>{if(e.key!=='Enter')return;const s=e.target.value.trim().toLowerCase();e.target.value='';const m=s.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(m)accept({x:Number(m[1]),y:Number(m[2])});else if(s==='fit'||s==='zoom')fit();else if(s==='undo')undo();else if(s==='redo')undo(true);else if(s==='rectangle'||s==='rect')setTool('rectangle');else if(names[s])setTool(s);else if(s==='erase')setTool('delete');else if(!s)finish();else notify('Unknown command: '+s)};
document.onkeydown=e=>{if(e.target.matches('input,select'))return;if(e.key==='Escape'){points=[];selected=-1;setTool('select')}else if(e.key==='Enter')finish();else if(e.key==='Delete'&&selected>=0){mutate(()=>doc.entities.splice(selected,1));selected=-1;render()}else if(e.ctrlKey&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();undo(e.key.toLowerCase()==='y')}};
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;W=r.width;H=r.height;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);render()}).observe(canvas);
try{const saved=localStorage.getItem('cadforge');if(saved){const d=JSON.parse(saved);validate(d);doc=d}}catch(e){}syncLayers();setTool('select');




