'use strict';
// Mesh extrusion and an orthographic 3D inspection workspace.
let mode3D=false,orbitDrag=null,camera3={yaw:-.7,pitch:.65,scale:3},meshCenter={x:0,y:0,z:0};
function polygonArea(ps){let sum=0;for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length];sum+=a.x*b.y-b.x*a.y}return sum/2}
function triangulatePolygon(input){let ps=input.map(p=>({...p}));if(ps.length>2&&distance(ps[0],ps.at(-1))<1e-8)ps.pop();if(ps.length<3)throw Error('At least three boundary vertices required.');if(polygonArea(ps)<0)ps.reverse();const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);let changed=true;while(changed&&ps.length>3){changed=false;for(let i=0;i<ps.length;i++){if(Math.abs(cross(ps[(i+ps.length-1)%ps.length],ps[i],ps[(i+1)%ps.length]))<1e-10){ps.splice(i,1);changed=true;break}}}const ids=ps.map((_,i)=>i),tris=[];let guard=ps.length**2;while(ids.length>3&&guard-->0){let found=false;for(let i=0;i<ids.length;i++){const a=ids[(i+ids.length-1)%ids.length],b=ids[i],c=ids[(i+1)%ids.length];if(cross(ps[a],ps[b],ps[c])<=1e-10)continue;const inside=ids.some(j=>j!==a&&j!==b&&j!==c&&cross(ps[a],ps[b],ps[j])>=-1e-10&&cross(ps[b],ps[c],ps[j])>=-1e-10&&cross(ps[c],ps[a],ps[j])>=-1e-10);if(inside)continue;tris.push([a,b,c]);ids.splice(i,1);found=true;break}if(!found)throw Error('Boundary must be a simple polygon without holes or intersections.')}if(ids.length!==3)throw Error('Unable to triangulate boundary.');tris.push([...ids]);return{ps,tris}}
function makeExtrusion(boundary,height,name='Extrusion'){if(!Number.isFinite(height)||height<=0)throw Error('Height must be positive.');const {ps,tris}=triangulatePolygon(boundary),n=ps.length,vertices=[...ps.map(p=>({...p,z:0})),...ps.map(p=>({...p,z:height}))],faces=[];for(const t of tris){faces.push([...t].reverse());faces.push(t.map(i=>i+n))}for(let i=0;i<n;i++){const j=(i+1)%n;faces.push([i,j,j+n],[i,j+n,i+n])}return{name,vertices,faces,color:layer().color}}
async function extrude(){const e=doc.entities[selected];if(!e||(e.type!=='circle'&&!(e.type==='polyline'&&e.closed))){notify('Select a closed polyline or circle in Model space first.');return}const raw=await cadPrompt('Extrusion height','20');if(raw===null)return;const ps=e.type==='circle'?Array.from({length:64},(_,i)=>({x:e.center.x+e.radius*Math.cos(i*Math.PI/32),y:e.center.y+e.radius*Math.sin(i*Math.PI/32)})):e.points;try{const mesh=makeExtrusion(ps,Number(raw));mutate(()=>{doc.solids??=[];doc.solids.push(mesh)});show3D();notify('Extruded to a triangle mesh. Source boundary remains in Model space.')}catch(err){notify(err.message)}}
async function box3D(){const raw=await cadPrompt('Box width, depth, height','100,60,30');if(raw===null)return;const [w,d,h]=raw.split(',').map(Number);if(raw.split(',').length!==3||![w,d,h].every(v=>Number.isFinite(v)&&v>0)){notify('Enter three positive dimensions separated by commas.');return}const mesh=makeExtrusion([{x:0,y:0},{x:w,y:0},{x:w,y:d},{x:0,y:d}],h,'Box');mutate(()=>{doc.solids??=[];doc.solids.push(mesh)});show3D()}
function fit3D(){const vs=(doc.solids||[]).flatMap(s=>s.vertices);if(!vs.length)return;const bounds=['x','y','z'].map(k=>[Math.min(...vs.map(p=>p[k])),Math.max(...vs.map(p=>p[k]))]);meshCenter={x:(bounds[0][0]+bounds[0][1])/2,y:(bounds[1][0]+bounds[1][1])/2,z:(bounds[2][0]+bounds[2][1])/2};const size=Math.hypot(...bounds.map(b=>b[1]-b[0]));camera3.scale=Math.min(W,H)*.7/Math.max(1,size)}
function show3D(){mode3D=true;clearSelection();dt.textContent='3D mesh workspace / Orthographic';badge.textContent='ORBIT';fit3D();render();notify('Drag to orbit; wheel to zoom. Meshes support extrusion and OBJ export. Return to Model for drafting.')}
function showModel(){mode3D=false;badge.textContent='TOP';dt.textContent='Drawing 1 / Model space';fit();render()}
function project3(p){const x=p.x-meshCenter.x,y=p.y-meshCenter.y,z=p.z-meshCenter.z,cy=Math.cos(camera3.yaw),sy=Math.sin(camera3.yaw),cp=Math.cos(camera3.pitch),sp=Math.sin(camera3.pitch),u=x*cy-y*sy,v=x*sy+y*cy;return{x:W/2+u*camera3.scale,y:H/2-(v*sp+z*cp)*camera3.scale,depth:v*cp-z*sp}}
const beforeMeshRender=render;render=function(){if(!mode3D){beforeMeshRender();return}ctx.clearRect(0,0,W,H);ctx.fillStyle='#151d27';ctx.fillRect(0,0,W,H);const faces=[];for(const s of doc.solids||[]){const ps=s.vertices.map(project3);for(const f of s.faces)faces.push({ps:f.map(i=>ps[i]),color:shadeMeshFace(s.color,s.vertices,f),depth:f.reduce((v,i)=>v+ps[i].depth,0)/f.length})}faces.sort((a,b)=>b.depth-a.depth);for(const f of faces){ctx.beginPath();f.ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();const signed=(f.ps[1].x-f.ps[0].x)*(f.ps[2].y-f.ps[0].y)-(f.ps[1].y-f.ps[0].y)*(f.ps[2].x-f.ps[0].x);if(signed>=0)continue;ctx.globalAlpha=1;ctx.fillStyle=f.color;ctx.fill();ctx.strokeStyle=f.color;ctx.lineWidth=.3;ctx.stroke()}for(const [axis,color]of [['x','#ef7676'],['y','#83cc8b'],['z','#82aafa']]){const a=project3(meshCenter),b=project3({...meshCenter,[axis]:meshCenter[axis]+30});ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle=color;ctx.font='12px Segoe UI';ctx.fillText(axis.toUpperCase(),b.x,b.y)}$('status').textContent=`3D | ${(doc.solids||[]).length} meshes | ${faces.length} triangles`;$('entityKind').textContent='3D mesh workspace'};
const meshDown=canvas.onpointerdown,meshMove=canvas.onpointermove,meshUp=canvas.onpointerup,meshWheel=canvas.onwheel;
canvas.onpointerdown=e=>{if(!mode3D){meshDown(e);return}canvas.setPointerCapture(e.pointerId);orbitDrag={x:e.clientX,y:e.clientY,yaw:camera3.yaw,pitch:camera3.pitch}};
canvas.onpointermove=e=>{if(!mode3D){meshMove(e);return}if(orbitDrag){camera3.yaw=orbitDrag.yaw+(e.clientX-orbitDrag.x)*.008;camera3.pitch=Math.max(-1.5,Math.min(1.5,orbitDrag.pitch+(e.clientY-orbitDrag.y)*.008));render()}};
canvas.onpointerup=e=>{orbitDrag=null;meshUp(e)};canvas.onpointercancel=()=>{orbitDrag=null;pan=null};canvas.onwheel=e=>{if(!mode3D){meshWheel(e);return}e.preventDefault();camera3.scale=Math.max(.01,Math.min(1000,camera3.scale*Math.exp(-e.deltaY*.001)));render()};
const draftSetTool=setTool;setTool=function(t){if(mode3D)showModel();draftSetTool(t)};
function exportOBJ(){if(!doc.solids?.length){notify('Create a box or extrusion first.');return}const out=['# CadForge triangle meshes; drawing units'],safe=s=>s.replace(/[^a-z0-9_-]/gi,'_');let offset=1;for(const s of doc.solids){out.push('o '+safe(s.name));for(const p of s.vertices)out.push(`v ${p.x} ${p.y} ${p.z}`);for(const f of s.faces)out.push('f '+f.map(i=>i+offset).join(' '));offset+=s.vertices.length}download('drawing.obj',out.join('\n')+'\n','text/plain');notify('OBJ exported. Mesh geometry is separate from 2D DXF output.')}
async function clearMeshes(){if(!doc.solids?.length)return;if(!await cadConfirm('Remove all meshes? Undo can restore them.'))return;mutate(()=>doc.solids=[]);render()}
group('3D Mesh',[['Extrude',extrude],['Box',box3D],['Orbit view',show3D],['Model 2D',showModel],['Fit meshes',()=>{fit3D();render()}],['Export OBJ',exportOBJ],['Clear meshes',clearMeshes]]);
const meshCommand=$('command').onkeydown;$('command').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const s=e.target.value.trim().toLowerCase(),actions={extrude,box:box3D,orbit:show3D,model:showModel,obj:exportOBJ};if(actions[s]){e.target.value='';actions[s]();return}}meshCommand(e)};
const meshValidate=validate;validate=function(d){meshValidate(d);if(d.solids){if(!Array.isArray(d.solids))throw Error('Invalid meshes');for(const s of d.solids){if(typeof s.name!=='string'||!/^#[0-9a-f]{6}$/i.test(s.color)||!Array.isArray(s.vertices)||!Array.isArray(s.faces)||s.vertices.length>1000000||s.faces.length>2000000)throw Error('Invalid mesh');if(!s.vertices.every(p=>p&&[p.x,p.y,p.z].every(Number.isFinite))||!s.faces.every(f=>Array.isArray(f)&&f.length===3&&f.every(i=>Number.isInteger(i)&&i>=0&&i<s.vertices.length)))throw Error('Invalid mesh geometry')}}};
const selectionUndo=undo;undo=function(redo=false){selectionSet.clear();selected=-1;selectionUndo(redo);if(mode3D){fit3D();render()}};
const meshFit=fit;fit=function(){if(mode3D){fit3D();render()}else meshFit()};
for(const b of tabbar.querySelectorAll('button'))b.onclick=()=>{tabbar.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));ribbon.querySelectorAll('.rgroup').forEach((g,i)=>{g.style.display=b.textContent==='Home'||(b.textContent==='Insert'&&[0,5].includes(i))||(b.textContent==='Annotate'&&[2,5].includes(i))||(b.textContent==='View'&&[3,6,7].includes(i))||(b.textContent==='Manage'&&[4,6,7].includes(i))?'block':'none'})};
const clearNew=$('new').onclick;$('new').onclick=async()=>{const before=doc;await clearNew();if(before!==doc){clearSelection();mode3D=false;badge.textContent='TOP';dt.textContent='Drawing 1 / Model space';render()}};
notify('Ready: 2D drafting, blocks, hatching, saved views and 3D mesh extrusion.');




function shadeMeshFace(color,vertices,face){const [a,b,c]=face.map(i=>vertices[i]),u={x:b.x-a.x,y:b.y-a.y,z:b.z-a.z},v={x:c.x-a.x,y:c.y-a.y,z:c.z-a.z},n={x:u.y*v.z-u.z*v.y,y:u.z*v.x-u.x*v.z,z:u.x*v.y-u.y*v.x},length=Math.hypot(n.x,n.y,n.z)||1;const shade=.4+.6*Math.max(0,(n.x*.35-n.y*.45+n.z*.8)/length);return '#'+[1,3,5].map(i=>Math.round(parseInt(color.slice(i,i+2),16)*shade).toString(16).padStart(2,'0')).join('')}
