'use strict';
// Closed profiles and explicitly additive/subtractive extrusion workflows.
function profileFromLines(lines){if(lines.length<3)throw Error('Select at least three connected lines forming a closed outline.');const tolerance=1e-6,nodes=[],edges=[];const node=p=>{let i=nodes.findIndex(q=>distance(p,q.p)<=tolerance);if(i<0){i=nodes.length;nodes.push({p:{...p},edges:[]})}return i};for(const e of lines){if(e.type!=='line')throw Error('Join profile accepts LINE entities only.');const a=node(e.points[0]),b=node(e.points[1]);if(a===b)throw Error('Zero-length edge in profile.');const i=edges.length;edges.push([a,b]);nodes[a].edges.push(i);nodes[b].edges.push(i)}if(nodes.some(n=>n.edges.length!==2))throw Error('Outline is open or branches. Every endpoint must meet exactly one other line.');const used=new Set(),ps=[];let n=edges[0][0],start=n;while(used.size<edges.length){ps.push({...nodes[n].p});const i=nodes[n].edges.find(i=>!used.has(i));if(i===undefined)break;used.add(i);n=edges[i][0]===n?edges[i][1]:edges[i][0];if(n===start)break}if(n!==start||used.size!==edges.length)throw Error('Select a single closed loop, without separate loops.');triangulatePolygon(ps);return ps}
function ensureEntityIDs(){const seen=new Set();for(const e of doc.entities){if(!e.uuid||seen.has(e.uuid))e.uuid=gid();seen.add(e.uuid)}}
ensureEntityIDs();
const profileMutation=mutate;mutate=function(fn){return profileMutation(()=>{fn();ensureEntityIDs()})};
async function joinProfile(){try{const ids=chosen();if(!ids.length)throw Error('Select connected lines first. Use Shift-click or Window select.');const boundary=profileFromLines(ids.map(i=>doc.entities[i])),name=doc.entities[ids[0]].layer;mutate(()=>{const discard=new Set(ids);doc.entities=doc.entities.filter((e,i)=>!discard.has(i));doc.entities.push({type:'polyline',closed:true,points:boundary,layer:name})});clearSelection();selected=doc.entities.length-1;selectionSet.add(selected);setTool('select');notify('Connected lines joined into a closed extrusion profile. Click Extrude.')}catch(err){await showMessage('Cannot join profile',err.message)}}
async function showMessage(title,message){notify(title+': '+message);await cadConfirm(title+' — '+message)}
function closedProfiles(){return doc.entities.map((e,i)=>({e,i})).filter(({e})=>e.type==='circle'||e.type==='polyline'&&e.closed)}
function boundaryOf(e){if(e.type==='circle')return Array.from({length:64},(_,i)=>({x:e.center.x+e.radius*Math.cos(i*Math.PI/32),y:e.center.y+e.radius*Math.sin(i*Math.PI/32)}));if(e.type==='polyline'&&e.closed)return structuredClone(e.points);throw Error('Source is not a closed extrusion profile.')}
function featureMesh(feature){const e=doc.entities.find(e=>e.uuid===feature.profile);if(!e)throw Error('The source profile was deleted. Select another closed profile and extrude again.');const mesh=makeExtrusion(boundaryOf(e),Math.abs(feature.height),'Extrusion');mesh.vertices.forEach(p=>p.z+=feature.startZ+(feature.height<0?feature.height:0));return mesh}
// The CSG worker executes complex operations without blocking drafting input.
booleanMeshes=function(a,b,operation){if(!['union','subtract','intersect'].includes(operation))throw Error('Invalid operation.');if(a.faces.length+b.faces.length>100000)throw Error('Input exceeds 100000 triangles.');return csgToMesh(meshToCSG(a)[operation](meshToCSG(b)),operation+' result',a.color)};
async function computeBoolean(a,b,op){if(typeof Worker==='undefined')return booleanMeshes(a,b,op);const code=booleanWorkerSource();const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'})),worker=new Worker(url);URL.revokeObjectURL(url);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{worker.terminate();reject(Error('Operation exceeded 45 seconds. Try simpler profiles or smaller meshes.'))},45000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(Error(e.data.error)):resolve(e.data.result)};worker.onerror=e=>{clearTimeout(timer);worker.terminate();reject(Error(e.message||'Mesh computation failed.'))};worker.postMessage({a,b,op})})}
let computingMesh=false,extrusionGeneration=0;
applyBoolean=async function(op){if(computingMesh)return;const ia=Number($('meshA').value),ib=Number($('meshB').value),a=doc.solids?.[ia],b=doc.solids?.[ib];if(!a||!b||ia===ib){await showMessage('Choose operands','Choose two different meshes in Mesh A and Mesh B.');return}computingMesh=true;notify(`Computing ${op}…`);try{const result=await computeBoolean(a,b,op);if(doc.solids?.[ia]!==a||doc.solids?.[ib]!==b)throw Error('The drawing changed during computation; operation cancelled.');mutate(()=>{doc.solids=doc.solids.filter((s,i)=>i!==ia&&i!==ib);if(result.faces.length)doc.solids.push(result)});show3D();notify(result.faces.length?`${op} completed: ${result.faces.length} triangles.`:'Result is empty. Undo restores operands.')}catch(err){await showMessage('Boolean failed',err.message)}finally{computingMesh=false}};
const extrusionDialog=document.createElement('dialog');extrusionDialog.id='extrusionDialog';extrusionDialog.innerHTML='<form id="extrusionForm"><h2>Extrude a closed profile</h2><label for="extrusionProfile">Source outline</label><select id="extrusionProfile"></select><label for="extrusionDepth">Extrusion depth</label><input id="extrusionDepth" type="number" value="20" step="any" required><label for="extrusionStart">Start elevation Z</label><input id="extrusionStart" type="number" value="0" step="any" required><label for="extrusionOperation">Result</label><select id="extrusionOperation"><option value="new">Create a separate part</option><option value="union">Add material to an existing part</option><option value="subtract">Cut material from an existing part</option></select><label for="extrusionTarget">Existing part</label><select id="extrusionTarget"></select><p id="extrusionHelp">Depth extends from Start Z. Sketch lines must form a closed outline. Source changes take effect with Update extrusion.</p><p id="extrusionError" role="alert"></p><div class="actions"><button type="button" id="extrusionCancel">Cancel</button><button id="extrusionApply" type="submit">Extrude</button></div></form>';document.body.append(extrusionDialog);
const extrusionCSS=document.createElement('style');extrusionCSS.textContent='#extrusionDialog{width:480px}#extrusionDialog select{width:100%;margin:6px 0}#extrusionHelp{color:#aabbd0;line-height:1.5}#extrusionError{color:#ffaf91}';document.head.append(extrusionCSS);
// Each outline is listed by its 1-based position in the list, its size and its lower-left corner, and the chosen outline is highlighted on the canvas.
const extrusionOutlines=new Map();
function profileLabel(e,position,total){const pts=boundaryOf(e),xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),x0=Math.min(...xs),y0=Math.min(...ys),n=v=>String(+v.toFixed(2)),size=e.type==='circle'?`Ø${n(e.radius*2)}`:`${n(Math.max(...xs)-x0)} × ${n(Math.max(...ys)-y0)}`;return `${position} of ${total}: ${e.type==='circle'?'Circle':'Closed outline'} ${size} at (${n(x0)}, ${n(y0)}) · layer ${e.layer}`}
function drawExtrusionHighlight(){if(!extrusionDialog.open||mode3D)return;const pts=extrusionOutlines.get($('extrusionProfile').value);if(!pts||pts.length<2)return;ctx.save();ctx.beginPath();pts.forEach((p,i)=>{const s=screen(p);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y)});ctx.closePath();ctx.fillStyle='rgba(255,203,102,0.22)';ctx.fill();ctx.strokeStyle='#ffcb66';ctx.lineWidth=3;ctx.stroke();ctx.restore()}
const extrusionPrevRender=render;render=function(...a){const r=extrusionPrevRender.apply(this,a);try{drawExtrusionHighlight()}catch(err){console.error(err)}return r};
extrude=async function(){extrusionGeneration++;if(mode3D)showModel();const ids=chosen();if(ids.length>=3&&ids.every(i=>doc.entities[i].type==='line')){try{const ps=profileFromLines(ids.map(i=>doc.entities[i]));mutate(()=>doc.entities.push({type:'polyline',points:ps,closed:true,layer:doc.entities[ids[0]].layer}));clearSelection();selected=doc.entities.length-1;selectionSet.add(selected)}catch(err){await showMessage('Cannot extrude lines',err.message+' Use Join profile after closing the outline.');return}}const available=closedProfiles();if(!available.length){await showMessage('No closed profile','Open lines cannot define a face. Close the outline, select its edges, and choose Join profile. Then choose Extrude.');return}ensureEntityIDs();extrusionOutlines.clear();for(const {e} of available)extrusionOutlines.set(e.uuid,boundaryOf(e));$('extrusionProfile').replaceChildren(...available.map(({e},n)=>new Option(profileLabel(e,n+1,available.length),e.uuid)));const chosenSource=available.find(({i})=>i===selected)||available.at(-1);$('extrusionProfile').value=chosenSource.e.uuid;const meshes=doc.solids||[];$('extrusionTarget').replaceChildren(...meshes.map((m,i)=>new Option(`${i+1}: ${m.name}`,String(i))));const currentMesh=Number($('meshA').value);$('extrusionTarget').value=String(currentMesh>=0&&currentMesh<meshes.length?currentMesh:0);$('extrusionOperation').value=meshes.length?'union':'new';$('extrusionDepth').value='20';$('extrusionStart').value='0';$('extrusionError').textContent='';extrusionDialog.showModal();render();$('extrusionDepth').focus();$('extrusionDepth').select()};
$('extrusionProfile').onchange=()=>render();{const nativeClose=extrusionDialog.close.bind(extrusionDialog);extrusionDialog.close=function(...a){const r=nativeClose(...a);extrusionOutlines.clear();render();return r}}
$('extrusionCancel').onclick=()=>{extrusionGeneration++;extrusionDialog.close()};extrusionDialog.oncancel=e=>{e.preventDefault();document.getElementById('extrusionCancel').click()};
$('extrusionForm').onsubmit=async e=>{e.preventDefault();if(computingMesh)return;const height=Number($('extrusionDepth').value),startZ=Number($('extrusionStart').value),operation=$('extrusionOperation').value,profile=$('extrusionProfile').value,index=Number($('extrusionTarget').value),target=doc.solids?.[index];if(!Number.isFinite(height)||height===0||!Number.isFinite(startZ)){$('extrusionError').textContent='Enter a nonzero depth and a finite start elevation.';return}if(operation!=='new'&&!target){$('extrusionError').textContent='Choose an existing part or create a separate part.';return}computingMesh=true;$('extrusionApply').disabled=true;$('extrusionError').textContent='Computing extrusion…';try{const generation=extrusionGeneration,feature={profile,height,startZ,operation};let result=featureMesh(feature);if(operation!=='new'){result=await computeBoolean(target,result,operation);if(!result.faces.length)throw Error('This operation leaves an empty part. Change the depth, elevation or source profile.')}if(generation!==extrusionGeneration){notify('Extrusion cancelled.');return}result.name=operation==='new'?'Extrusion':target.name;result.extrusionProgram=operation==='new'?{base:null,features:[feature]}:target.extrusionProgram?{base:structuredClone(target.extrusionProgram.base),features:[...structuredClone(target.extrusionProgram.features),feature]}:{base:{name:target.name,color:target.color,vertices:structuredClone(target.vertices),faces:structuredClone(target.faces)},features:[feature]};mutate(()=>{doc.solids??=[];if(operation==='new')doc.solids.push(result);else doc.solids[index]=result});extrusionDialog.close();show3D();notify(operation==='new'?'New extruded part created.':operation==='union'?'Existing part updated with added material.':'Material cut from existing part.')}catch(err){$('extrusionError').textContent=err.message}finally{computingMesh=false;$('extrusionApply').disabled=false}};
async function updateExtrusion(){const index=Number($('meshA').value),target=doc.solids?.[index],program=target?.extrusionProgram;if(!program){await showMessage('No linked extrusion','This part has no editable extrusion history. Select its new outline and choose Extrude → Add material, or create a new linked extrusion.');return}if(computingMesh)return;computingMesh=true;notify('Rebuilding extrusion from source profiles…');try{let result=program.base?structuredClone(program.base):null;for(const feature of program.features){const mesh=featureMesh(feature);result=feature.operation==='new'||!result?mesh:await computeBoolean(result,mesh,feature.operation)}if(doc.solids?.[index]!==target)throw Error('Part changed while rebuilding.');if(!result.faces.length)throw Error('Updated extrusion is empty.');result.name=target.name;result.extrusionProgram=structuredClone(program);mutate(()=>doc.solids[index]=result);show3D();notify('Part rebuilt from the current source outlines.')}catch(err){await showMessage('Update failed',err.message)}finally{computingMesh=false}}
// Replace captured Extrude button handlers and expose profile controls.
for(const b of ribbon.querySelectorAll('button'))if(b.textContent==='Extrude')b.onclick=()=>extrude();
const profileGroup=document.createElement('div');profileGroup.className='rgroup';const profileButtons=document.createElement('div');profileButtons.className='rbuttons';for(const [label,fn]of [['Join profile',joinProfile],['Extrude profile',()=>extrude()],['Update extrusion',updateExtrusion]]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;profileButtons.append(b)}const profileCaption=document.createElement('strong');profileCaption.textContent='Profiles / Features';profileGroup.append(profileButtons,profileCaption);ribbon.append(profileGroup);
for(const b of tabbar.querySelectorAll('button')){const old=b.onclick;b.onclick=()=>{old();profileGroup.style.display=['Home','View','Insert'].includes(b.textContent)?'block':'none'}}
const profileCommand=$('command').onkeydown;$('command').onkeydown=e=>{if(e.key==='Enter'){const s=e.target.value.trim().toLowerCase();if(['join','joinprofile','extrude','updateextrusion'].includes(s)){e.preventDefault();e.target.value='';({join:joinProfile,joinprofile:joinProfile,extrude:()=>extrude(),updateextrusion:updateExtrusion})[s]();return}}profileCommand(e)};
// Prevent global Enter/Escape handlers from cancelling an active extrusion form.
const profileKeys=document.onkeydown;document.onkeydown=e=>{if(extrusionDialog.open)return;profileKeys(e)};
// Discover closed line loops so a freshly drawn outline appears in Extrude immediately.
const pendingProfiles=new Map();
const savedClosedProfiles=closedProfiles;
closedProfiles=function(){pendingProfiles.clear();const result=savedClosedProfiles(),lines=doc.entities.map((e,i)=>({e,i})).filter(({e})=>e.type==='line'&&!e.hatch&&!e.group);if(lines.length>5000)return result;const visited=new Set();for(let root=0;root<lines.length;root++){if(visited.has(root))continue;const component=[],queue=[root];visited.add(root);while(queue.length){const k=queue.pop(),line=lines[k];component.push(line);for(let j=0;j<lines.length;j++){if(visited.has(j))continue;if(line.e.points.some(a=>lines[j].e.points.some(b=>distance(a,b)<=1e-6))){visited.add(j);queue.push(j)}}}if(component.length<3)continue;try{const ps=profileFromLines(component.map(x=>x.e)),uuid=gid(),e={type:'polyline',closed:true,points:ps,layer:component[0].e.layer,uuid};pendingProfiles.set(uuid,{entity:e,sources:component.map(x=>x.e.uuid)});result.push({e,i:Math.max(...component.map(x=>x.i)),fromLines:true})}catch(err){/* Open/branching edges are left for explicit Join profile. */}}return result};
const initialFeatureMesh=featureMesh;featureMesh=function(feature){const candidate=pendingProfiles.get(feature.profile);if(!candidate)return initialFeatureMesh(feature);const mesh=makeExtrusion(boundaryOf(candidate.entity),Math.abs(feature.height),'Extrusion');mesh.vertices.forEach(p=>p.z+=feature.startZ+(feature.height<0?feature.height:0));return mesh};
const sourceProfileMutation=mutate;mutate=function(fn){return sourceProfileMutation(()=>{fn();for(const solid of doc.solids||[])for(const feature of solid.extrusionProgram?.features||[]){const candidate=pendingProfiles.get(feature.profile);if(candidate&&!doc.entities.some(e=>e.uuid===feature.profile)){const remove=new Set(candidate.sources);doc.entities=doc.entities.filter(e=>!remove.has(e.uuid));doc.entities.push(structuredClone(candidate.entity))}}})};

const extrusionSchemaValidate=validate;validate=function(d){extrusionSchemaValidate(d);for(const mesh of d.solids||[]){const program=mesh.extrusionProgram;if(!program)continue;if(!Array.isArray(program.features)||!program.features.length)throw Error('Invalid extrusion history.');for(const f of program.features)if(!f||typeof f.profile!=='string'||!Number.isFinite(f.height)||f.height===0||!Number.isFinite(f.startZ)||!['new','union','subtract','intersect'].includes(f.operation))throw Error('Invalid extrusion feature.');if(program.base)extrusionSchemaValidate({layers:d.layers,entities:[],solids:[program.base]})}};

function booleanWorkerSource(){const library=document.getElementById('cadforge-csg').textContent;return library+'\n'+meshToCSG.toString()+'\n'+csgToMesh.toString()+'\nconst booleanMeshes='+booleanMeshes.toString()+';\nonmessage=function(e){try{postMessage({result:booleanMeshes(e.data.a,e.data.b,e.data.op)})}catch(err){postMessage({error:err.message})}}'}
