'use strict';
// Local vector sheet preview and PDF download; no pop-up window required.
const plotDialog=document.createElement('dialog');plotDialog.id='plotDialog';plotDialog.innerHTML='<h2>Drawing sheet</h2><div class="sheetControls"><label>Paper <select id="sheetPaper"><option>A4</option><option>A3</option><option>LETTER</option></select></label><label>Orientation <select id="sheetOrientation"><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label><label>Scale <select id="sheetScale"><option value="fit">Fit drawing</option><option value="1">1:1</option><option value="2">1:2</option><option value="5">1:5</option><option value="10">1:10</option></select></label></div><div id="sheetPreview"></div><p id="sheetNote">Drawing units are treated as millimetres for fixed scales.</p><div class="actions"><button id="sheetPDF">Download PDF</button><button id="sheetSVG">Download SVG</button><button id="sheetClose">Close</button></div>';document.body.append(plotDialog);
const sheetCSS=document.createElement('style');sheetCSS.textContent='#plotDialog{width:min(1000px,95vw);max-width:95vw}#plotDialog .sheetControls{display:flex;gap:20px}#plotDialog .sheetControls label{margin:0}#sheetPreview{background:white;margin:12px 0;max-height:60vh;overflow:auto}#sheetPreview svg{display:block;width:100%;height:auto;max-height:55vh}#sheetNote{color:#aebfd2}';document.head.append(sheetCSS);
function entityBounds(entities){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const e of entities){const ps=e.type==='circle'?[{x:e.center.x-e.radius,y:e.center.y-e.radius},{x:e.center.x+e.radius,y:e.center.y+e.radius}]:e.type==='text'?[e.points[0],{x:e.points[0].x+e.text.length*e.height*.6,y:e.points[0].y+e.height}]:e.points;for(const p of ps){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}}return Number.isFinite(minX)?{minX,minY,maxX,maxY}:{minX:0,minY:0,maxX:100,maxY:100}}
function sheetConfig(){const paper=$('sheetPaper').value,portrait=$('sheetOrientation').value==='portrait';let [width,height]=paper==='A3'?[420,297]:paper==='LETTER'?[279.4,215.9]:[297,210];if(portrait)[width,height]=[height,width];const entities=doc.entities.filter(e=>doc.layers.find(l=>l.name===e.layer)?.visible),b=entityBounds(entities),margin=12,fitted=Math.min((width-margin*2)/Math.max(1,b.maxX-b.minX),(height-margin*2)/Math.max(1,b.maxY-b.minY)),scale=$('sheetScale').value==='fit'?fitted:1/Number($('sheetScale').value),offsetX=(width-(b.maxX-b.minX)*scale)/2-b.minX*scale,offsetY=(height-(b.maxY-b.minY)*scale)/2-b.minY*scale;return{width,height,scale,offsetX,offsetY,entities,overflow:scale>fitted+1e-9}}
function sheetSVG(config){const {width,height,scale,offsetX,offsetY,entities}=config,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));const X=x=>offsetX+x*scale,Y=y=>height-offsetY-y*scale;let content='';for(const e of entities){if(e.type==='circle')content+=`<circle cx="${X(e.center.x)}" cy="${Y(e.center.y)}" r="${e.radius*scale}"/>`;else if(e.type==='text')content+=`<text x="${X(e.points[0].x)}" y="${Y(e.points[0].y)}" font-size="${e.height*scale}" font-family="Arial" stroke="none" fill="black">${esc(e.text)}</text>`;else content+=`<${e.closed?'polygon':'polyline'} points="${e.points.map(p=>X(p.x)+','+Y(p.y)).join(' ')}"/>`}return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}mm" height="${height}mm" viewBox="0 0 ${width} ${height}"><rect width="${width}" height="${height}" fill="white"/><g fill="none" stroke="black" stroke-width=".25">${content}</g></svg>`}
function makeSheetPDF(config){const pt=72/25.4,{width,height,scale,offsetX,offsetY,entities}=config,X=x=>(offsetX+x*scale)*pt,Y=y=>(offsetY+y*scale)*pt,num=v=>Number(v.toFixed(5)).toString(),content=['0 G','0 g','0.7 w'];const point=p=>`${num(X(p.x))} ${num(Y(p.y))}`;for(const e of entities){if(e.type==='text'){const text=e.text.replace(/[^\x20-\x7e]/g,'?').replace(/[\\()]/g,'\\$&');content.push(`BT /F1 ${num(e.height*scale*pt)} Tf ${point(e.points[0])} Td (${text}) Tj ET`)}else if(e.type==='circle'){const x=X(e.center.x),y=Y(e.center.y),r=e.radius*scale*pt,k=r*.552284749831;content.push(`${num(x+r)} ${num(y)} m`,`${num(x+r)} ${num(y+k)} ${num(x+k)} ${num(y+r)} ${num(x)} ${num(y+r)} c`,`${num(x-k)} ${num(y+r)} ${num(x-r)} ${num(y+k)} ${num(x-r)} ${num(y)} c`,`${num(x-r)} ${num(y-k)} ${num(x-k)} ${num(y-r)} ${num(x)} ${num(y-r)} c`,`${num(x+k)} ${num(y-r)} ${num(x+r)} ${num(y-k)} ${num(x+r)} ${num(y)} c S`)}else{content.push(point(e.points[0])+' m');for(const p of e.points.slice(1))content.push(point(p)+' l');if(e.closed)content.push('h');content.push('S')}}const stream=content.join('\n')+'\n',objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>',`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${num(width*pt)} ${num(height*pt)}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}endstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((obj,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return pdf}
function refreshSheet(){const c=sheetConfig();$('sheetPreview').innerHTML=sheetSVG(c);$('sheetNote').textContent=c.overflow?'The fixed scale exceeds this sheet. Choose Fit drawing, larger paper, or a smaller scale.':'Preview and PDF use the same drawing extents. Fixed scales treat drawing units as millimetres.'}
plotSheet=function(){if(!doc.entities.length){notify('Draw 2D geometry before creating a sheet.');return}if(mode3D)showModel();refreshSheet();plotDialog.showModal()};
for(const id of ['sheetPaper','sheetOrientation','sheetScale'])$(id).onchange=refreshSheet;
$('sheetClose').onclick=()=>plotDialog.close();$('sheetPDF').onclick=()=>download('drawing-sheet.pdf',makeSheetPDF(sheetConfig()),'application/pdf');$('sheetSVG').onclick=()=>download('drawing-sheet.svg',sheetSVG(sheetConfig()),'image/svg+xml');
for(const b of ribbon.querySelectorAll('button'))if(['Plot','Print sheet'].includes(b.textContent))b.onclick=()=>plotSheet();
const sheetKeys=document.onkeydown;document.onkeydown=e=>{if(plotDialog.open)return;sheetKeys(e)};
// Exports offer a visible file link and inspectable content in embedded browsers.
const exportDialog=document.createElement('dialog');exportDialog.id='exportDialog';exportDialog.innerHTML='<h2 id="exportTitle">Export file</h2><p>Use Download file to save. If your embedded browser prevents downloads, open CadForge.html in Chrome or Edge. The file contents are also available below.</p><a id="exportLink" class="exportDownload">Download file</a><label for="exportContent">File contents</label><textarea id="exportContent" readonly spellcheck="false"></textarea><div class="actions"><button id="exportClose">Close</button></div>';document.body.append(exportDialog);
const exportCSS=document.createElement('style');exportCSS.textContent='#exportDialog{width:700px;max-width:95vw}#exportContent{width:100%;height:220px;background:#101923;color:#dce8f4;border:1px solid #66798f;font:11px Consolas}.exportDownload{display:inline-block;background:#38679b;padding:10px 18px;color:white;text-decoration:none;border-radius:4px}';document.head.append(exportCSS);
let exportURL=null;download=function(name,text,type){if(exportURL)URL.revokeObjectURL(exportURL);exportURL=URL.createObjectURL(new Blob([text],{type}));$('exportTitle').textContent=name;$('exportLink').href=exportURL;$('exportLink').download=name;$('exportContent').value=text;exportDialog.showModal()};
$('exportClose').onclick=()=>exportDialog.close();
const exportKeys=document.onkeydown;document.onkeydown=e=>{if(exportDialog.open)return;exportKeys(e)};
