(async()=>{
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const noop=()=>{},elements={},ctx=new Proxy({}, {get:()=>noop,set:()=>true});
class Element{constructor(id=''){this.id=id;this.value=id==='layer'?'0':'#63d9c0';this.checked=true;this.children=[];this.dataset={};this.style={};this.classList={toggle:noop};this.files=[];this.textContent='';this.innerHTML=''}append(...xs){this.children.push(...xs)}prepend(...xs){this.children.unshift(...xs)}after(){}before(){}replaceChildren(...xs){this.children=xs}click(){this.onclick?.()}querySelector(s){return this.querySelectorAll(s)[0]||el('query'+s)}focus(){}select(){}showModal(){}close(){}querySelectorAll(s){const all=this.children.flatMap(c=>[c,...(c.children||[])]);return all.filter(c=>s==='button'?c instanceof Element&&c.tag==='button':s==='.rgroup'?c.className==='rgroup':false)}matches(){return false}getContext(){return ctx}getBoundingClientRect(){return{width:1000,height:700}}setPointerCapture(){}}
const el=id=>elements[id]??=new Element(id);let answers=[];
const sandbox={document:{body:el('body'),head:el('head'),getElementById:el,createElement:tag=>{const e=new Element();e.tag=tag;return e},querySelector:el,querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem:noop},ResizeObserver:class{observe(){}},Option:class{},devicePixelRatio:1,structuredClone,console,assert,Blob,URL,setTimeout,prompt:()=>answers.shift()??null,confirm:()=>true,window:{print:noop,open:()=>null,addEventListener:noop}};
vm.createContext(sandbox);const html=fs.readFileSync(require('node:path').join(__dirname,'CadForge.html'),'utf8');for(const match of html.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g))vm.runInContext(match[1],sandbox);
sandbox.testPrompt=async()=>answers.shift()??null;vm.runInContext('cadPrompt=testPrompt;cadConfirm=async()=>true',sandbox);const run=s=>vm.runInContext('(async()=>{'+s+'})()',sandbox);
await run("W=1000;H=700;doc.entities=[];setTool('rectangle');await accept({x:0,y:0});await accept({x:100,y:60});selected=0;selectionSet=new Set([0]);");
answers=['Fixture'];await run("await createBlock();assert.equal(doc.blocks.Fixture.items.length,1)");
answers=['Fixture'];await run("await startInsert();await accept({x:200,y:0});assert.equal(doc.entities.length,2);assert.notEqual(doc.entities[0].group,doc.entities[1].group)");
await run("selected=1;selectionSet=new Set([1]);setTool('move');await accept({x:0,y:0});await accept({x:5,y:10});assert.equal(doc.entities[1].points[0].x,205);assert.equal(doc.entities[1].points[0].y,10)");
answers=['10'];await run("selected=0;selectionSet=new Set([0]);await hatch();assert.ok(doc.entities.length>2);const before=doc.entities.length;undo();assert.equal(doc.entities.length,2);undo(true);assert.equal(doc.entities.length,before)");
await run("selected=0;selectionSet=new Set([0]);explode();assert.ok(!doc.entities[0].group);selected=0;selectionSet=new Set([0]);explode();assert.equal(doc.entities[0].type,'line')");
await run("clearSelection();doc.entities=[{type:'line',layer:'0',points:[{x:0,y:0},{x:4,y:0}]},{type:'line',layer:'0',points:[{x:10,y:-10},{x:10,y:10}]}];extendAt({x:3,y:0});assert.equal(doc.entities[0].points[1].x,10)");
await run("doc.entities=[{type:'line',layer:'0',points:[{x:0,y:0},{x:20,y:0}]},{type:'line',layer:'0',points:[{x:0,y:0},{x:0,y:20}]}];selected=0;selectionSet=new Set([0,1])");answers=['5'];await run("await chamfer();assert.equal(doc.entities.length,3);assert.equal(doc.entities[0].points[0].x,5);assert.equal(doc.entities[1].points[0].y,5)");
await run("const box=makeExtrusion([{x:0,y:0},{x:10,y:0},{x:10,y:20},{x:0,y:20}],30,'Test');assert.equal(box.vertices.length,8);assert.equal(box.faces.length,12);const edges={};for(const f of box.faces)for(let i=0;i<3;i++){const key=[f[i],f[(i+1)%3]].sort((a,b)=>a-b).join(',');edges[key]=(edges[key]||0)+1}assert.ok(Object.values(edges).every(n=>n===2));let volume=0;for(const f of box.faces){const [a,b,c]=f.map(i=>box.vertices[i]);volume+=(a.x*(b.y*c.z-b.z*c.y)-a.y*(b.x*c.z-b.z*c.x)+a.z*(b.x*c.y-b.y*c.x))/6}assert.ok(Math.abs(volume-6000)<1e-8);const concave=makeExtrusion([{x:0,y:0},{x:10,y:0},{x:10,y:5},{x:5,y:5},{x:5,y:10},{x:0,y:10}],3);assert.equal(concave.faces.length,20);doc.solids=[box,concave];validate(doc);show3D();render();showModel();const saved=JSON.parse(JSON.stringify(doc));validate(saved);assert.throws(()=>validate({...saved,solids:[{...box,faces:[[0,1,999]]}]}));");
answers=['Sheet A'];await run("await saveLayout();assert.ok(doc.layouts['Sheet A']);view.x=999");answers=['Sheet A'];await run("await restoreLayout();assert.notEqual(view.x,999)");
await run("const imported=importDXF(exportDXF());assert.equal(imported.doc.entities.length,doc.entities.length);assert.equal(imported.skipped,0)");
console.log('PASS: bundled initialization; block create/insert; grouped transforms; hatch undo/redo; explode; extend; chamfer; layout restoration; convex/concave extrusion; watertight mesh edges; signed volume; project validation; 3D rendering; DXF output');
// Additional compatibility regression checks.
await run("doc={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[{type:'line',layer:'0',group:'demo',points:[{x:2,y:3},{x:12,y:3}]},{type:'circle',layer:'0',group:'demo',center:{x:7,y:8},radius:2}]};clearSelection();const blockText=exportDXF();assert.ok(blockText.includes('BLOCKS'));assert.ok(blockText.includes('INSERT'));const br=importDXF(blockText);assert.equal(br.skipped,0);assert.equal(br.doc.entities.length,2);assert.equal(br.doc.entities[0].group,br.doc.entities[1].group);assert.equal(br.doc.entities[0].points[0].x,2);assert.equal(br.doc.entities[1].radius,2);assert.ok(br.doc.blocks.CF_INSTANCE_1)");
await run("const arcText=dxfWrapped([{type:'ARC',pairs:[[8,'0'],[10,0],[20,0],[40,10],[50,0],[51,90]]}]);const ar=importDXF(arcText);assert.equal(ar.approximated,1);assert.ok(Math.abs(ar.doc.entities[0].points[0].x-10)<1e-8);assert.ok(Math.abs(ar.doc.entities[0].points.at(-1).y-10)<1e-8);const bulgeText=dxfWrapped([{type:'LWPOLYLINE',pairs:[[8,'0'],[70,0],[10,0],[20,0],[42,1],[10,10],[20,0]]}]);const curved=importDXF(bulgeText);assert.equal(curved.approximated,1);assert.equal(curved.doc.entities[0].points.at(-1).x,10);assert.ok(Math.min(...curved.doc.entities[0].points.map(p=>p.y))<-4.9);assert.throws(()=>importDXF('AutoCAD Binary DXF'))");
console.log('PASS: native DXF BLOCK/INSERT round trip, ARC endpoints, bulge tessellation, binary DXF rejection');

await run("const A=makeExtrusion([{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}],10,'A'),B=makeExtrusion([{x:5,y:0},{x:15,y:0},{x:15,y:10},{x:5,y:10}],10,'B');const volume=m=>m.faces.reduce((v,f)=>{const [a,b,c]=f.map(i=>m.vertices[i]);return v+(a.x*(b.y*c.z-b.z*c.y)-a.y*(b.x*c.z-b.z*c.x)+a.z*(b.x*c.y-b.y*c.x))/6},0);for(const [op,expected]of [['union',1500],['subtract',500],['intersect',500]]){const result=booleanMeshes(A,B,op);assert.ok(Math.abs(volume(result)-expected)<1e-5,op);validate({layers:doc.layers,entities:[],solids:[result]})}assert.equal(booleanMeshes(A,A,'subtract').faces.length,0);const distant=structuredClone(B);distant.vertices.forEach(p=>p.x+=100);assert.equal(booleanMeshes(A,distant,'intersect').faces.length,0);assert.ok(Math.abs(volume(booleanMeshes(A,distant,'union'))-2000)<1e-5);doc.solids=[A,B];");
console.log('PASS: mesh union, subtraction, intersection, coplanar boxes, identical subtraction and disjoint results with signed-volume checks');
await run("clearSelection();doc={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[{type:'polyline',uuid:'base',layer:'0',closed:true,points:[{x:0,y:0},{x:20,y:0},{x:20,y:20},{x:0,y:20}]}],solids:[makeExtrusion([{x:0,y:0},{x:20,y:0},{x:20,y:20},{x:0,y:20}],10,'Existing part')]};const loop=[{x:20,y:5},{x:30,y:5},{x:30,y:15},{x:20,y:15}];for(let i=0;i<4;i++)doc.entities.push({type:'line',uuid:'new'+i,layer:'0',points:[loop[i],loop[(i+1)%4]]});const profiles=closedProfiles();assert.equal(profiles.length,2);const newProfile=profiles.find(p=>p.fromLines);assert.ok(newProfile);const feature={profile:newProfile.e.uuid,height:10,startZ:0,operation:'union'};const addition=featureMesh(feature);assert.equal(addition.faces.length,12);const updated=await computeBoolean(doc.solids[0],addition,'union');const volume=m=>m.faces.reduce((v,f)=>{const [a,b,c]=f.map(i=>m.vertices[i]);return v+(a.x*(b.y*c.z-b.z*c.y)-a.y*(b.x*c.z-b.z*c.x)+a.z*(b.x*c.y-b.y*c.x))/6},0);assert.ok(Math.abs(volume(updated)-5000)<1e-7);updated.extrusionProgram={base:structuredClone(doc.solids[0]),features:[feature]};mutate(()=>doc.solids[0]=updated);assert.equal(doc.entities.length,2);assert.ok(doc.entities.some(e=>e.uuid===feature.profile&&e.closed));assert.ok(Math.abs(volume(featureMesh(feature))-1000)<1e-7);assert.throws(()=>profileFromLines([{type:'line',points:[{x:0,y:0},{x:10,y:0}]},{type:'line',points:[{x:10,y:0},{x:10,y:10}]},{type:'line',points:[{x:10,y:10},{x:0,y:10}]}]),/open/);mode3D=false;clearSelection();doc.entities=[{type:'line',layer:'0',points:[{x:1.25,y:1.75},{x:3.25,y:1.75}]}];view={x:0,y:0,scale:100};W=1000;H=700;setTool('select');canvas.onpointerdown({button:0,offsetX:700,offsetY:175,pointerId:1,shiftKey:false});assert.equal(selected,0);let prevented=false;document.onkeydown({key:'Escape',target:document.getElementById('command'),preventDefault(){prevented=true}});assert.ok(prevented);assert.equal(selected,-1);const pdf=makeSheetPDF({width:297,height:210,scale:1,offsetX:12,offsetY:12,entities:[{type:'circle',center:{x:20,y:20},radius:5},{type:'text',points:[{x:10,y:10}],height:4,text:'Sheet test'}]});assert.ok(pdf.startsWith('%PDF-1.4'));assert.ok(pdf.includes('/MediaBox [0 0 841.88976 595.27559]'));const xref=Number(pdf.split('startxref')[1].trim().split(String.fromCharCode(10))[0]);assert.equal(pdf.slice(xref,xref+4),'xref');");
console.log('PASS: closed-line profile discovery, additive extrusion volume, source retention, open-outline errors, raw off-grid selection, Escape from command input, vector PDF header/media box/xref');
el('cadforge-csg').textContent=fs.readFileSync(require('node:path').join(__dirname,'csg-library.js'),'utf8');
const workerCode=vm.runInContext('booleanWorkerSource()',sandbox);new vm.Script(workerCode);let workerResult;const workerSandbox={postMessage:msg=>workerResult=msg};vm.createContext(workerSandbox);vm.runInContext(workerCode,workerSandbox);const actualSaved=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'Extrusion-After.cadforge.json'),'utf8'));const savedVolume=actualSaved.solids[0].faces.reduce((v,f)=>{const [a,b,c]=f.map(i=>actualSaved.solids[0].vertices[i]);return v+(a.x*(b.y*c.z-b.z*c.y)-a.y*(b.x*c.z-b.z*c.x)+a.z*(b.x*c.y-b.y*c.x))/6},0);assert.ok(Math.abs(savedVolume-5000)<1e-6);assert.equal(actualSaved.solids.length,1);assert.equal(actualSaved.solids[0].extrusionProgram.features.length,1);const actualBase=actualSaved.solids[0].extrusionProgram.base;workerSandbox.onmessage({data:{a:actualBase,b:actualBase,op:'union'}});assert.ok(workerResult.result);assert.ok(!workerResult.error);assert.equal(workerResult.result.vertices.length,8);
console.log('PASS: actual browser-generated additive part (volume 5000), saved feature history and executable worker-source syntax/union');
await run("showModel();clearSelection();doc={layers:[{name:'0',color:'#63d9c0',visible:true}],entities:[]};const c=$('command');const enter=s=>{c.value=s;c.onkeydown({key:'Enter',target:c,preventDefault(){}})};enter('PLINE');assert.equal(tool,'polyline');enter('0,0');enter('@10<0');enter('@0,10');enter('@-10,0');enter('C');assert.equal(doc.entities.length,1);assert.ok(doc.entities[0].closed);assert.equal(doc.entities[0].points[1].x,10);clearSelection();setTool('select');enter('REC');assert.equal(tool,'rectangle');setTool('select');enter('');assert.equal(tool,'rectangle');c.onkeydown({key:'ArrowUp',target:c,preventDefault(){}});assert.equal(c.value,'REC');enter('Z');assert.ok(uiZoomPending);enter('E');assert.ok(!uiZoomPending);enter('DIMLINEAR');assert.equal(tool,'dimension');");
console.log('PASS: PLINE/RECTANG/DIMLINEAR aliases, polar coordinates, closed outline, command repeat/recall and Z E extents');
})().catch(e=>{console.error(e);process.exitCode=1});









