/* CadForge extended workspace */
const extraStyle=document.createElement('style');extraStyle.textContent=`
body{font-size:12px;background:#171a20}header{height:42px;background:#252a33;padding:0 12px;gap:12px}h1{font-size:18px;color:#eef2f7}header button{padding:5px 9px}button,input,select{border-radius:2px;background:#303641;border-color:#49515f}button:hover,button.active{background:#3c638d}#ribbon{height:114px;background:#30353e;border-bottom:1px solid #12151b;display:flex;padding:6px 12px;gap:12px;overflow-x:auto}.rgroup{border-right:1px solid #515762;padding-right:12px;min-width:140px}.rgroup strong{display:block;font-size:11px;color:#abb7c7;text-align:center;margin-top:5px}.rbuttons{display:flex;flex-wrap:wrap;gap:4px;max-width:285px}.rbuttons button{min-width:65px;height:34px}.tabs{height:29px;background:#22262e;padding:6px 20px;word-spacing:20px}.drawingtab{height:27px;padding:6px 18px;background:#20242b;color:#b5c9e0}main{height:calc(100vh - 322px)}aside{width:210px;padding:12px;background:#272c35}#tools{display:none}#properties{width:240px;background:#272c35;padding:14px;overflow:auto}#properties input,#properties select{width:100%;margin:4px 0}#properties button{margin-top:5px}#historylog{height:30px;background:#20242a;font:12px Consolas;padding:7px 16px;white-space:nowrap;overflow:hidden;color:#b4bdc9}footer{height:50px;background:#252a32}#hint{background:#202833cc;padding:7px;border-radius:3px}.viewbadge{position:absolute;right:16px;top:16px;border:2px solid #7d8da0;padding:18px;color:#c9d6e4;background:#303a47}.statusbar{height:30px;background:#252b35;padding:5px 15px;display:flex;gap:20px;color:#a6b8cc}@media(max-width:1000px){#properties{width:180px}aside{width:160px}header span{display:none}}`;
document.head.append(extraStyle);
const tabbar=document.createElement('div');tabbar.className='tabs';tabbar.textContent='HOME   INSERT   ANNOTATE   VIEW   MANAGE';document.querySelector('header').after(tabbar);
const ribbon=document.createElement('div');ribbon.id='ribbon';tabbar.after(ribbon);
function group(title,items){const g=document.createElement('div');g.className='rgroup';const bs=document.createElement('div');bs.className='rbuttons';for(const [label,fn,t]of items){const b=document.createElement('button');b.textContent=label;b.onclick=fn;if(t)b.dataset.tool=t;bs.append(b)}const caption=document.createElement('strong');caption.textContent=title;g.append(bs,caption);ribbon.append(g)}
const drawItems=['line','polyline','rectangle','circle','text'].map(t=>[names[t],()=>setTool(t),t]);
names.arc='Arc';names.dimension='Dimension';names.rotate='Rotate';names.scale='Scale';names.mirror='Mirror';names.offset='Offset';names.trim='Trim';
group('Draw', [...drawItems,['Arc',()=>setTool('arc'),'arc']]);
group('Modify',['move','copy','rotate','scale','mirror','offset','trim','delete'].map(t=>[names[t],()=>setTool(t),t]));
group('Annotation',[['Dimension',()=>setTool('dimension'),'dimension'],['Text',()=>setTool('text'),'text'],['Measure',measure]]);
group('View / Output',[['Extents',fit],['Undo',()=>undo()],['Redo',()=>undo(true)],['Plot',()=>window.print()]]);
const dt=document.createElement('div');dt.className='drawingtab';dt.textContent='Drawing 1  /  Model space';ribbon.after(dt);
const badge=document.createElement('div');badge.className='viewbadge';badge.textContent='TOP';$('viewport').append(badge);
const props=document.createElement('section');props.id='properties';props.innerHTML='<strong>PROPERTIES</strong><label id="entityKind">No entity selected</label><label>Entity layer</label><select id="entityLayer"></select><label>Text content</label><input id="entityText"><label>Text height / Circle radius</label><input id="entitySize" type="number" min="0.001" step="0.1"><button id="applyProps">Apply changes</button><hr><small>Select an entity to inspect it.<br><br>2D model space<br>World coordinate system<br>DXF R12 export<br><br>Dimension and arc geometry is exported as editable primitives.</small>';
document.querySelector('main').append(props);
const log=document.createElement('div');log.id='historylog';document.querySelector('footer').before(log);
const sb=document.createElement('div');sb.className='statusbar';sb.innerHTML='<span>MODEL</span><span>F8 Ortho</span><span>F9 Grid snap</span><span>Endpoint snap</span><span>Units: drawing units</span><span>LOCAL</span>';document.querySelector('footer').after(sb);
const baseNotify=notify;notify=function(s){baseNotify(s);log.textContent=s};
const baseRender=render;render=function(){baseRender();const e=doc.entities[selected];$('entityKind').textContent=e?e.type.toUpperCase()+' · '+(selected+1):'No entity selected';if(document.activeElement?.closest('#properties'))return;$('entityLayer').replaceChildren(...doc.layers.map(l=>new Option(l.name,l.name)));if(e){$('entityLayer').value=e.layer;$('entityText').value=e.text||'';$('entitySize').value=e.type==='circle'?e.radius:e.type==='text'?e.height:''}else{$('entityText').value='';$('entitySize').value=''}};
$('applyProps').onclick=()=>{const e=doc.entities[selected];if(!e)return;const size=Number($('entitySize').value);if(['circle','text'].includes(e.type)&&(!Number.isFinite(size)||size<=0)){notify('Enter a positive size.');return}mutate(()=>{e.layer=$('entityLayer').value;if(e.type==='text'){e.text=$('entityText').value;e.height=size}if(e.type==='circle')e.radius=size})};
function measure(){const e=doc.entities[selected];if(!e){notify('Select an entity to measure.');return}let len=0,area=0;if(e.type==='circle'){len=2*Math.PI*e.radius;area=Math.PI*e.radius**2}else{const ps=e.points;for(let i=1;i<ps.length;i++)len+=distance(ps[i-1],ps[i]);if(e.closed){len+=distance(ps.at(-1),ps[0]);for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length];area+=a.x*b.y-b.x*a.y}area=Math.abs(area)/2}}notify(`Length: ${len.toFixed(4)}   Area: ${area.toFixed(4)}`)}
function transformEntity(e,fn){if(e.center)e.center=fn(e.center);else e.points=e.points.map(fn)}
function lineIntersection(a,b,c,d){const den=(b.x-a.x)*(d.y-c.y)-(b.y-a.y)*(d.x-c.x);if(Math.abs(den)<1e-10)return null;const t=((c.x-a.x)*(d.y-c.y)-(c.y-a.y)*(d.x-c.x))/den,u=((c.x-a.x)*(b.y-a.y)-(c.y-a.y)*(b.x-a.x))/den;return t>1e-9&&t<1-1e-9&&u>=0&&u<=1?{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y),t}:null}
function trimAt(p){const idx=hit(p),e=doc.entities[idx];if(!e||e.type!=='line'){notify('Trim supports intersecting straight lines; click the end to remove.');return}const cuts=[];doc.entities.forEach((other,i)=>{if(i===idx||other.type!=='line')return;const q=lineIntersection(...e.points,...other.points);if(q)cuts.push(q)});if(!cuts.length){notify('No crossing line found.');return}const removeStart=distance(p,e.points[0])<distance(p,e.points[1]);cuts.sort((a,b)=>a.t-b.t);mutate(()=>e.points[removeStart?0:1]=removeStart?cuts[0]:cuts.at(-1));notify('Line trimmed.')}
const baseAccept=accept;accept=async function(p){
if(tool==='trim'){trimAt(p);return}
if(['rotate','scale','mirror','offset'].includes(tool)){
 if(selected<0){selected=hit(p);render();notify('Specify base point (offset: click once after selecting).');return}
 const source=doc.entities[selected];
 if(tool==='offset'){const raw=await cadPrompt('Offset distance (signed for straight lines)','5');if(raw===null)return;const amount=Number(raw);if(!Number.isFinite(amount)){notify('Invalid distance');return}const e=structuredClone(source);if(e.type==='circle'){if(e.radius+amount<=0){notify('Offset would produce a nonpositive radius.');return}e.radius+=amount}else if(e.type==='line'){const [a,b]=e.points,len=distance(a,b);if(len<1e-9)return;const dx=-(b.y-a.y)/len*amount,dy=(b.x-a.x)/len*amount;transformEntity(e,q=>({x:q.x+dx,y:q.y+dy}))}else{notify('Offset currently supports lines and circles.');return}add(e);return}
 points.push(p);if(tool==='mirror'&&points.length<2){notify('Specify second point of mirror axis.');return}
 const a=points[0];let fn,factor=1;
 if(tool==='rotate'){const raw=await cadPrompt('Rotation angle in degrees','90');if(raw===null){points=[];return}const angle=Number(raw)*Math.PI/180;if(!Number.isFinite(angle)){points=[];return}fn=q=>({x:a.x+(q.x-a.x)*Math.cos(angle)-(q.y-a.y)*Math.sin(angle),y:a.y+(q.x-a.x)*Math.sin(angle)+(q.y-a.y)*Math.cos(angle)})}
 if(tool==='scale'){const raw=await cadPrompt('Scale factor','2');if(raw===null){points=[];return}factor=Number(raw);if(!Number.isFinite(factor)||factor<=0){points=[];notify('Enter a positive scale factor.');return}fn=q=>({x:a.x+(q.x-a.x)*factor,y:a.y+(q.y-a.y)*factor})}
 if(tool==='mirror'){const b=points[1],len=distance(a,b);if(len<1e-9){points=[];return}const ux=(b.x-a.x)/len,uy=(b.y-a.y)/len;fn=q=>{const vx=q.x-a.x,vy=q.y-a.y,dot=vx*ux+vy*uy;return{x:a.x+2*dot*ux-vx,y:a.y+2*dot*uy-vy}}}
 mutate(()=>{transformEntity(source,fn);if(source.type==='circle')source.radius*=factor;if(source.type==='text')source.height*=factor});points=[];notify('Transformation complete. Text stays horizontal.');return
}
if(tool==='arc'){points.push(p);if(points.length===1)notify('Specify arc start point.');else if(points.length===2)notify('Specify arc end point (counterclockwise).');else{const [c,a,b]=points,r=distance(c,a);if(r>1e-9){let start=Math.atan2(a.y-c.y,a.x-c.x),end=Math.atan2(b.y-c.y,b.x-c.x);while(end<=start)end+=Math.PI*2;const count=Math.max(16,Math.ceil((end-start)*32)),ps=[];for(let i=0;i<=count;i++){const t=start+(end-start)*i/count;ps.push({x:c.x+r*Math.cos(t),y:c.y+r*Math.sin(t)})}add({type:'polyline',points:ps,closed:false});notify('Arc created as segmented polyline.')}points=[]}render();return}
if(tool==='dimension'){points.push(p);if(points.length===1)notify('Specify second measurement point.');else if(points.length===2)notify('Specify dimension line position.');else{const [a,b,pos]=points,len=distance(a,b);if(len>1e-9){const ux=(b.x-a.x)/len,uy=(b.y-a.y)/len,nx=-uy,ny=ux,off=(pos.x-a.x)*nx+(pos.y-a.y)*ny,A={x:a.x+nx*off,y:a.y+ny*off},B={x:b.x+nx*off,y:b.y+ny*off},size=Math.min(3,len/8),ents=[{type:'line',points:[a,A]},{type:'line',points:[b,B]},{type:'line',points:[A,B]},{type:'text',points:[{x:(A.x+B.x)/2+nx*2,y:(A.y+B.y)/2+ny*2}],text:len.toFixed(2),height:3}];for(const [p,dir]of [[A,1],[B,-1]])for(const side of [-1,1])ents.push({type:'line',points:[p,{x:p.x+dir*ux*size+nx*side*size*.35,y:p.y+dir*uy*size+ny*side*size*.35}]});mutate(()=>doc.entities.push(...ents.map(e=>({...e,layer:layer().name}))));notify('Dimension created as independent lines and text.')}points=[]}render();return}
baseAccept(p)};
const baseCommand=$('command').onkeydown;$('command').onkeydown=e=>{if(e.key==='Enter'){const s=e.target.value.trim().toLowerCase(),aliases={l:'line',pl:'polyline',c:'circle',rec:'rectangle',m:'move',co:'copy',e:'delete',ro:'rotate',sc:'scale',mi:'mirror',o:'offset',tr:'trim',dim:'dimension',a:'arc'};if(s==='measure'){measure();e.target.value='';return}if(aliases[s])e.target.value=aliases[s];const relative=e.target.value.match(/^@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)$/);if(relative&&points.length){const a=points.at(-1);accept({x:a.x+Number(relative[1]),y:a.y+Number(relative[2])});e.target.value='';return}}baseCommand(e)};
const baseKeys=document.onkeydown;document.onkeydown=e=>{if(e.key==='F8'||e.key==='F9'){e.preventDefault();const el=$(e.key==='F8'?'ortho':'snap');el.checked=!el.checked;notify((e.key==='F8'?'Ortho':'Snap')+(el.checked?' on':' off'));return}baseKeys(e)};
const printStyle=document.createElement('style');printStyle.textContent='@media print{header,.tabs,#ribbon,.drawingtab,aside,#properties,footer,#historylog,.statusbar,#hint,.viewbadge{display:none!important}main{height:95vh}body{background:white}canvas{background:#10151d} }';document.head.append(printStyle);
setTool('select');


// Ribbon tabs expose the relevant command panels.
tabbar.textContent='';
for(const tabName of ['Home','Insert','Annotate','View','Manage']){
 const button=document.createElement('button');button.textContent=tabName;button.style.cssText='padding:3px 14px;border:0;margin-top:-4px';
 button.onclick=()=>{tabbar.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));ribbon.querySelectorAll('.rgroup').forEach((g,i)=>{g.style.display=tabName==='Home'||(tabName==='Insert'&&i===0)||(tabName==='Annotate'&&i===2)||(tabName==='View'&&i===3)||(tabName==='Manage'&&i===4)?'block':'none'})};
 tabbar.append(button);
}
group('Project / Layers',[['Open',()=>$('file').click()],['Save',()=>$('save').click()],['Add layer',()=>$('addLayer').click()],['DXF',()=>$('dxf').click()]]);
tabbar.querySelector('button').click();

